{
  "hash": "cd8899a1be8d86f8e19f7655da793b2e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Visual Analytics for Data Discovery\"\nauthor: \"Cao Jinming\"\ndate: \"20 May 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n---\n\n## Overview\n\nThis report applies visual analytics to a real-world motor insurance portfolio from a Spanish non-life insurer. The exercise brief asks for R-based visual analytics that go beyond dashboard reporting and help discover factors linked to portfolio **profitability** and **volatility**.\n\nThe report is organised in the following structure: context first, analytical sandbox, data preparation, univariate exploration, bivariate analysis, statistical validation, and final findings. The analysis uses the [Mendeley motor portfolio data](https://data.mendeley.com/datasets/sw4jmdb2sm/1).\n\nTwo analytical definitions are used throughout the report:\n\n-   **Profitability** is measured by aggregate `profit = total_premium - total_incurred` and by aggregate `loss_ratio = total_incurred / total_premium`. Lower loss ratio indicates better underwriting profitability before expenses.\n-   **Volatility** is measured by claim occurrence, claim frequency, capped individual loss ratio, high-loss policy rate, and upper-tail loss-ratio behaviour.\n\nThe main question is: *which portfolio segments show weaker profitability or higher volatility, and are those patterns visually and statistically defensible?*\n\n## Analytical sandbox\n\n### R packages and helper functions\n\nThe analytical sandbox uses `tidyverse` for data wrangling, `ggplot2` and extensions for visual analytics, and `knitr` for tabular reporting. Reusable import and portfolio-summary functions are stored in `TH_Ex/th_ex1_common.R` so that the report and slides can use the same definitions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(ggrepel)\n\nif (file.exists(\"TH_Ex/th_ex1_common.R\")) {\n  source(\"TH_Ex/th_ex1_common.R\")\n} else {\n  source(\"th_ex1_common.R\")\n}\n\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\nThe table below documents the packages and helper functions used in this report, including the self-created functions stored in `TH_Ex/th_ex1_common.R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsandbox_tools <- tribble(\n  ~type, ~name, ~purpose,\n  \"R package\", \"tidyverse\", \"Main workflow package for data wrangling, reshaping, factor handling, and `ggplot2` visualisation.\",\n  \"R package\", \"readxl\", \"Reads the Excel data dictionary supplied with the motor insurance dataset.\",\n  \"R package\", \"scales\", \"Formats axis labels and table values as Euro amounts, percentages, and comma-separated counts.\",\n  \"R package\", \"patchwork\", \"Combines multiple `ggplot2` charts into one visual layout for side-by-side comparison.\",\n  \"R package\", \"knitr\", \"Creates clean report tables from R data frames using `kable()`.\",\n  \"R package\", \"ggrepel\", \"Provides non-overlapping text-labelling functions for scatterplots when segment labels need to remain readable.\",\n  \"Self-created helper\", \"find_project_root()\", \"Locates the Quarto project root by searching upward for `_quarto.yml`, making file paths more robust.\",\n  \"Self-created helper\", \"project_path()\", \"Builds project-relative file paths from the detected project root.\",\n  \"Self-created helper\", \"ensure_th1_data()\", \"Checks whether the raw CSV and data dictionary exist locally; if not, downloads and extracts them from Mendeley Data.\",\n  \"Self-created helper\", \"load_th1_motor()\", \"Imports the semicolon-delimited motor portfolio CSV and creates derived analytical variables such as profit, loss ratio, claim flag, severity, and age bands.\",\n  \"Self-created helper\", \"portfolio_summary()\", \"Aggregates portfolio records by a selected segment and calculates exposure, premium, incurred loss, claims, profit, loss ratio, claim frequency, severity, and high-loss indicators.\",\n  \"Self-created helper\", \"money\", \"Reusable Euro currency labeller created with `scales::label_dollar()`.\",\n  \"Self-created helper\", \"pct\", \"Reusable percentage labeller created with `scales::label_percent()`.\",\n  \"Base R / utils\", \"download.file()\", \"Downloads the Mendeley data zip file when the raw data is not already available locally.\",\n  \"Base R / utils\", \"utils::unzip()\", \"Extracts the downloaded zip file so the CSV and Excel dictionary can be copied into the project data folder.\"\n)\n\nkable(sandbox_tools)\n```\n\n::: {.cell-output-display}\n\n\n|type                |name                |purpose                                                                                                                                                                              |\n|:-------------------|:-------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|R package           |tidyverse           |Main workflow package for data wrangling, reshaping, factor handling, and `ggplot2` visualisation.                                                                                   |\n|R package           |readxl              |Reads the Excel data dictionary supplied with the motor insurance dataset.                                                                                                           |\n|R package           |scales              |Formats axis labels and table values as Euro amounts, percentages, and comma-separated counts.                                                                                       |\n|R package           |patchwork           |Combines multiple `ggplot2` charts into one visual layout for side-by-side comparison.                                                                                               |\n|R package           |knitr               |Creates clean report tables from R data frames using `kable()`.                                                                                                                      |\n|R package           |ggrepel             |Provides non-overlapping text-labelling functions for scatterplots when segment labels need to remain readable.                                                                      |\n|Self-created helper |find_project_root() |Locates the Quarto project root by searching upward for `_quarto.yml`, making file paths more robust.                                                                                |\n|Self-created helper |project_path()      |Builds project-relative file paths from the detected project root.                                                                                                                   |\n|Self-created helper |ensure_th1_data()   |Checks whether the raw CSV and data dictionary exist locally; if not, downloads and extracts them from Mendeley Data.                                                                |\n|Self-created helper |load_th1_motor()    |Imports the semicolon-delimited motor portfolio CSV and creates derived analytical variables such as profit, loss ratio, claim flag, severity, and age bands.                        |\n|Self-created helper |portfolio_summary() |Aggregates portfolio records by a selected segment and calculates exposure, premium, incurred loss, claims, profit, loss ratio, claim frequency, severity, and high-loss indicators. |\n|Self-created helper |money               |Reusable Euro currency labeller created with `scales::label_dollar()`.                                                                                                               |\n|Self-created helper |pct                 |Reusable percentage labeller created with `scales::label_percent()`.                                                                                                                 |\n|Base R / utils      |download.file()     |Downloads the Mendeley data zip file when the raw data is not already available locally.                                                                                             |\n|Base R / utils      |utils::unzip()      |Extracts the downloaded zip file so the CSV and Excel dictionary can be copied into the project data folder.                                                                         |\n\n\n:::\n:::\n\n\n### Data source and import\n\nThe dataset is the open-access motor insurance portfolio from Mendeley Data. The helper function downloads and extracts the data if the CSV and data dictionary are not already available locally. The CSV is semicolon-delimited.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor <- load_th1_motor()\ndict <- read_excel(th1_dict_path)\n\nglimpse(motor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 55\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <fct> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ claim_flag                  <lgl> FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FA…\n$ profit                      <dbl> 279.5576, 546.6234, 315.7396, -2001.7291, …\n$ loss_ratio                  <dbl> 0.0000000, 0.0000000, 0.4246231, 4.4239104…\n$ loss_ratio_cap              <dbl> 0.0000000, 0.0000000, 0.4246231, 4.4239104…\n$ claim_frequency             <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ severity                    <dbl> NA, NA, 233.0130, 1293.1807, NA, NA, NA, N…\n$ driver_age_band             <fct> 46-55, 36-45, 36-45, 36-45, 36-45, 46-55, …\n$ vehicle_age_band            <fct> 21+, 21+, 21+, 21+, 21+, 21+, 21+, 8-12, 1…\n```\n\n\n:::\n:::\n\n\n### Portfolio size and derived variables\n\nThe imported portfolio contains policy-year records from 2022 to 2024. The table below documents the derived variables and summary functions used to construct the portfolio-size table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nderived_variable_reference <- tribble(\n  ~type, ~name, ~purpose,\n  \"Derived variable\", \"profit\", \"Measures underwriting result at policy-year level: total premium minus total incurred loss.\",\n  \"Derived variable\", \"loss_ratio\", \"Measures loss burden relative to premium: total incurred loss divided by total premium.\",\n  \"Derived variable\", \"loss_ratio_cap\", \"Caps individual loss ratio at the 99th percentile so plots are not dominated by extreme outliers.\",\n  \"Derived variable\", \"claim_flag\", \"Marks whether a policy-year has at least one claim; used for claim-record share and volatility checks.\",\n  \"Derived variable\", \"claim_frequency\", \"Standardises claim count by exposure: total claims divided by total exposure.\",\n  \"Derived variable\", \"severity\", \"Measures average incurred loss per claim; defined only for records with at least one claim.\",\n  \"Derived variable\", \"driver_age_band\", \"Groups driver age into bands for segment-level profitability and volatility comparison.\",\n  \"Derived variable\", \"vehicle_age_band\", \"Groups vehicle age into bands for segment-level profitability and volatility comparison.\",\n  \"Summary table\", \"portfolio_size\", \"Stores the headline portfolio-size, premium, incurred loss, profit, loss-ratio, and claim-share metrics displayed in this section.\"\n)\n\nkable(derived_variable_reference)\n```\n\n::: {.cell-output-display}\n\n\n|type             |name             |purpose                                                                                                                            |\n|:----------------|:----------------|:----------------------------------------------------------------------------------------------------------------------------------|\n|Derived variable |profit           |Measures underwriting result at policy-year level: total premium minus total incurred loss.                                        |\n|Derived variable |loss_ratio       |Measures loss burden relative to premium: total incurred loss divided by total premium.                                            |\n|Derived variable |loss_ratio_cap   |Caps individual loss ratio at the 99th percentile so plots are not dominated by extreme outliers.                                  |\n|Derived variable |claim_flag       |Marks whether a policy-year has at least one claim; used for claim-record share and volatility checks.                             |\n|Derived variable |claim_frequency  |Standardises claim count by exposure: total claims divided by total exposure.                                                      |\n|Derived variable |severity         |Measures average incurred loss per claim; defined only for records with at least one claim.                                        |\n|Derived variable |driver_age_band  |Groups driver age into bands for segment-level profitability and volatility comparison.                                            |\n|Derived variable |vehicle_age_band |Groups vehicle age into bands for segment-level profitability and volatility comparison.                                           |\n|Summary table    |portfolio_size   |Stores the headline portfolio-size, premium, incurred loss, profit, loss-ratio, and claim-share metrics displayed in this section. |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio_size <- tibble(\n  measure = c(\n    \"Policy-year records\",\n    \"Distinct insured IDs\",\n    \"Calendar years\",\n    \"Variables after derivation\",\n    \"Aggregate premium\",\n    \"Aggregate incurred loss\",\n    \"Aggregate profit\",\n    \"Aggregate loss ratio\",\n    \"Claim-record share\"\n  ),\n  value = c(\n    comma(nrow(motor)),\n    comma(n_distinct(motor$insured_id)),\n    paste(levels(motor$year), collapse = \", \"),\n    comma(ncol(motor)),\n    money(sum(motor$total_premium, na.rm = TRUE)),\n    money(sum(motor$total_incurred, na.rm = TRUE)),\n    money(sum(motor$profit, na.rm = TRUE)),\n    pct(sum(motor$total_incurred, na.rm = TRUE) / sum(motor$total_premium, na.rm = TRUE)),\n    pct(mean(motor$claim_flag, na.rm = TRUE))\n  )\n)\n\nkable(portfolio_size)\n```\n\n::: {.cell-output-display}\n\n\n|measure                    |value            |\n|:--------------------------|:----------------|\n|Policy-year records        |354,140          |\n|Distinct insured IDs       |185,678          |\n|Calendar years             |2022, 2023, 2024 |\n|Variables after derivation |55               |\n|Aggregate premium          |€105,079,669     |\n|Aggregate incurred loss    |€73,864,811      |\n|Aggregate profit           |€31,214,859      |\n|Aggregate loss ratio       |70.3%            |\n|Claim-record share         |14.3%            |\n\n\n:::\n:::\n\n\n-   Portfolio is profitable in aggregate before expenses.\n-   Aggregate totals can hide segment-level volatility.\n-   The remaining analysis focuses on distributions, outliers, and segment comparisons.\n\n### Data quality checks\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_tbl <- motor |>\n  summarise(across(everything(), ~sum(is.na(.x)))) |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"missing_records\") |>\n  filter(missing_records > 0) |>\n  mutate(missing_share = missing_records / nrow(motor)) |>\n  arrange(desc(missing_records))\n\nkable(missing_tbl, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|variable            | missing_records| missing_share|\n|:-------------------|---------------:|-------------:|\n|severity            |          303333|        0.8565|\n|fuel_type           |            1287|        0.0036|\n|vehicle_value       |             513|        0.0014|\n|loss_ratio          |              49|        0.0001|\n|loss_ratio_cap      |              49|        0.0001|\n|claim_frequency     |              49|        0.0001|\n|vehicle_age         |               2|        0.0000|\n|age_driving_licence |               2|        0.0000|\n|vehicle_age_band    |               2|        0.0000|\n\n\n:::\n:::\n\n\n-   Core premium and incurred-loss variables are mostly complete.\n-   `severity` has many missing values because it is defined only for claim records.\n-   Missing `fuel_type`, `vehicle_value`, `vehicle_age`, and `age_driving_licence` records are retained to avoid distorting exposure totals.\n\n## Task 1: Univariate visual analytics\n\nThis section applies the recommended univariate visual for each source column in the motor insurance portfolio. The approach is type-specific:\n\n-   identifiers are summarised with uniqueness and duplicate counts, not plotted as continuous numbers;\n-   categorical variables use count/composition bars, with top-N grouping for high-cardinality fields;\n-   ordinary numerical variables use a histogram plus boxplot;\n-   optional premium and incurred-loss variables are split into zero-versus-positive bars plus positive-value distributions;\n-   claim counts use count bars and a separate 0-claim versus 1-or-more-claims view.\n\n```{=html}\n<style>\n.observation-box {\n  background-color: #fff3cd;\n  border-left: 6px solid #d95f0e;\n  border-radius: 6px;\n  padding: 0.85rem 1rem;\n  margin: 1rem 0 1.25rem 0;\n}\n.observation-box strong {\n  color: #7a3e00;\n}\n</style>\n```\n\n### Recommended visual plan\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_profile <- motor |>\n  mutate(\n    year_numeric = as.numeric(as.character(year)),\n    licence_years_held = if_else(\n      !is.na(year_numeric) & !is.na(age_driving_licence),\n      year_numeric - age_driving_licence,\n      NA_real_\n    )\n  )\n\nprofile_spec <- tribble(\n  ~variable, ~variable_type, ~best_univariate_visual, ~what_to_look_for, ~visual_family, ~top_n,\n  \"insured_id\", \"ID\", \"Uniqueness count and duplicate count\", \"How many unique policies or customers exist; do not treat this as a normal numeric variable.\", \"id\", NA_real_,\n  \"year\", \"Time / ordinal categorical\", \"Bar chart plus line of record counts by year\", \"Which years have more policies.\", \"year\", NA_real_,\n  \"policy_type\", \"Categorical\", \"Bar chart / count plot\", \"Most common insurance coverage type.\", \"categorical\", NA_real_,\n  \"policy_status\", \"Categorical\", \"Bar chart\", \"Active versus cancelled policies.\", \"categorical\", NA_real_,\n  \"business_type\", \"Categorical\", \"Bar chart\", \"New business versus portfolio policies.\", \"categorical\", NA_real_,\n  \"payment_frequency\", \"Categorical\", \"Bar chart\", \"Annual, semiannual, or quarterly payment patterns.\", \"categorical\", NA_real_,\n  \"bonus_score\", \"Ordinal categorical\", \"Ordered bar chart\", \"Distribution of good, neutral, and bad claim history.\", \"ordinal\", NA_real_,\n  \"driver_age\", \"Numerical\", \"Histogram + boxplot\", \"Age distribution and young or old driver outliers.\", \"numeric\", NA_real_,\n  \"vehicle_age\", \"Numerical\", \"Histogram + boxplot\", \"Whether cars are mostly new or old.\", \"numeric\", NA_real_,\n  \"age_driving_licence\", \"Year variable\", \"Histogram or bar chart by licence year\", \"When drivers got their licence.\", \"numeric\", NA_real_,\n  \"licence_years_held\", \"Derived numerical\", \"Histogram + boxplot\", \"Approximate driving experience, calculated as year minus licence year.\", \"numeric\", NA_real_,\n  \"fuel_type\", \"Categorical\", \"Bar chart\", \"Diesel versus gasoline split.\", \"categorical\", NA_real_,\n  \"vehicle_value\", \"Numerical money/value\", \"Histogram + boxplot plus missing-value check\", \"Car value distribution, missing values, and expensive outliers.\", \"money\", NA_real_,\n  \"seats\", \"Discrete numerical / categorical\", \"Bar chart\", \"Common seat numbers, for example 4, 5, or 7.\", \"discrete\", NA_real_,\n  \"power_to_weight_ratio\", \"Numerical\", \"Histogram + boxplot\", \"Vehicle performance distribution and outliers.\", \"numeric\", NA_real_,\n  \"vehicle_brand\", \"High-cardinality categorical\", \"Horizontal bar chart of top 20 brands\", \"Most common brands; rare brands are grouped as Other.\", \"categorical\", 20,\n  \"municipality_type\", \"Categorical\", \"Bar chart\", \"Inland, coastal, and island distribution.\", \"categorical\", NA_real_,\n  \"circulation_area\", \"Categorical\", \"Bar chart\", \"Urban versus rural distribution.\", \"categorical\", NA_real_,\n  \"total_premium\", \"Numerical money\", \"Histogram + boxplot\", \"Overall price distribution and expensive policies.\", \"premium\", NA_real_,\n  \"liability_premium\", \"Numerical money\", \"Histogram + boxplot\", \"Cost of third-party liability coverage.\", \"premium\", NA_real_,\n  \"property_damage_premium\", \"Numerical money\", \"Histogram + boxplot\", \"Distribution of property damage premium.\", \"premium\", NA_real_,\n  \"theft_premium\", \"Optional premium\", \"Zero-versus-positive bar plus histogram of positive premiums\", \"Whether theft coverage is commonly purchased.\", \"optional_premium\", NA_real_,\n  \"fire_premium\", \"Optional premium\", \"Zero-versus-positive bar plus histogram of positive premiums\", \"Whether fire coverage is commonly purchased.\", \"optional_premium\", NA_real_,\n  \"glass_premium\", \"Optional premium\", \"Zero-versus-positive bar plus histogram of positive premiums\", \"Whether glass coverage is common.\", \"optional_premium\", NA_real_,\n  \"legal_protection_premium\", \"Optional premium\", \"Zero-versus-positive bar plus histogram of positive premiums\", \"Whether legal protection is commonly purchased.\", \"optional_premium\", NA_real_,\n  \"occupants_premium\", \"Optional premium\", \"Zero-versus-positive bar plus histogram of positive premiums\", \"Whether occupant injury coverage is common.\", \"optional_premium\", NA_real_,\n  \"total_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Usually many policies have 0 claims.\", \"claim_count\", NA_real_,\n  \"liability_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Number of liability claims.\", \"claim_count\", NA_real_,\n  \"liability_property_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Claims involving third-party property damage.\", \"claim_count\", NA_real_,\n  \"liability_injury_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Injury-related liability claims.\", \"claim_count\", NA_real_,\n  \"property_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Property damage claim frequency.\", \"claim_count\", NA_real_,\n  \"theft_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Theft claim frequency.\", \"claim_count\", NA_real_,\n  \"fire_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Fire claim frequency.\", \"claim_count\", NA_real_,\n  \"glass_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Glass claim frequency.\", \"claim_count\", NA_real_,\n  \"legal_protection_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Legal protection claim frequency.\", \"claim_count\", NA_real_,\n  \"occupants_claims\", \"Count\", \"Bar chart of claim-count values plus 0 versus 1+ claims\", \"Occupant injury claim frequency.\", \"claim_count\", NA_real_,\n  \"total_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Claim cost severity and extreme losses.\", \"incurred\", NA_real_,\n  \"liability_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Cost of liability claims.\", \"incurred\", NA_real_,\n  \"liability_property_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Cost of liability property damage.\", \"incurred\", NA_real_,\n  \"liability_injury_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Injury claim costs, likely very skewed.\", \"incurred\", NA_real_,\n  \"property_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Property damage claim costs.\", \"incurred\", NA_real_,\n  \"theft_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Theft claim costs.\", \"incurred\", NA_real_,\n  \"fire_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Fire claim costs.\", \"incurred\", NA_real_,\n  \"glass_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Glass claim costs.\", \"incurred\", NA_real_,\n  \"legal_protection_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Legal protection claim costs.\", \"incurred\", NA_real_,\n  \"occupants_incurred\", \"Numerical money\", \"Zero-versus-positive bar; log-scale histogram and boxplot for positive values\", \"Occupant injury claim costs.\", \"incurred\", NA_real_,\n  \"total_exposure\", \"Numerical\", \"Histogram + boxplot\", \"Full-year policies versus partial-year policies; check values above 1.\", \"exposure\", NA_real_,\n  \"liability_exposure\", \"Numerical\", \"Histogram + boxplot\", \"Exposure time for liability coverage.\", \"exposure\", NA_real_\n)\n\nmissing_from_data <- setdiff(profile_spec$variable, names(motor_profile))\nif (length(missing_from_data) > 0) {\n  stop(paste(\"Variables missing from motor_profile:\", paste(missing_from_data, collapse = \", \")))\n}\n\nprofile_spec |>\n  select(variable, variable_type, best_univariate_visual, what_to_look_for) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|variable                    |variable_type                    |best_univariate_visual                                                        |what_to_look_for                                                                             |\n|:---------------------------|:--------------------------------|:-----------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------|\n|insured_id                  |ID                               |Uniqueness count and duplicate count                                          |How many unique policies or customers exist; do not treat this as a normal numeric variable. |\n|year                        |Time / ordinal categorical       |Bar chart plus line of record counts by year                                  |Which years have more policies.                                                              |\n|policy_type                 |Categorical                      |Bar chart / count plot                                                        |Most common insurance coverage type.                                                         |\n|policy_status               |Categorical                      |Bar chart                                                                     |Active versus cancelled policies.                                                            |\n|business_type               |Categorical                      |Bar chart                                                                     |New business versus portfolio policies.                                                      |\n|payment_frequency           |Categorical                      |Bar chart                                                                     |Annual, semiannual, or quarterly payment patterns.                                           |\n|bonus_score                 |Ordinal categorical              |Ordered bar chart                                                             |Distribution of good, neutral, and bad claim history.                                        |\n|driver_age                  |Numerical                        |Histogram + boxplot                                                           |Age distribution and young or old driver outliers.                                           |\n|vehicle_age                 |Numerical                        |Histogram + boxplot                                                           |Whether cars are mostly new or old.                                                          |\n|age_driving_licence         |Year variable                    |Histogram or bar chart by licence year                                        |When drivers got their licence.                                                              |\n|licence_years_held          |Derived numerical                |Histogram + boxplot                                                           |Approximate driving experience, calculated as year minus licence year.                       |\n|fuel_type                   |Categorical                      |Bar chart                                                                     |Diesel versus gasoline split.                                                                |\n|vehicle_value               |Numerical money/value            |Histogram + boxplot plus missing-value check                                  |Car value distribution, missing values, and expensive outliers.                              |\n|seats                       |Discrete numerical / categorical |Bar chart                                                                     |Common seat numbers, for example 4, 5, or 7.                                                 |\n|power_to_weight_ratio       |Numerical                        |Histogram + boxplot                                                           |Vehicle performance distribution and outliers.                                               |\n|vehicle_brand               |High-cardinality categorical     |Horizontal bar chart of top 20 brands                                         |Most common brands; rare brands are grouped as Other.                                        |\n|municipality_type           |Categorical                      |Bar chart                                                                     |Inland, coastal, and island distribution.                                                    |\n|circulation_area            |Categorical                      |Bar chart                                                                     |Urban versus rural distribution.                                                             |\n|total_premium               |Numerical money                  |Histogram + boxplot                                                           |Overall price distribution and expensive policies.                                           |\n|liability_premium           |Numerical money                  |Histogram + boxplot                                                           |Cost of third-party liability coverage.                                                      |\n|property_damage_premium     |Numerical money                  |Histogram + boxplot                                                           |Distribution of property damage premium.                                                     |\n|theft_premium               |Optional premium                 |Zero-versus-positive bar plus histogram of positive premiums                  |Whether theft coverage is commonly purchased.                                                |\n|fire_premium                |Optional premium                 |Zero-versus-positive bar plus histogram of positive premiums                  |Whether fire coverage is commonly purchased.                                                 |\n|glass_premium               |Optional premium                 |Zero-versus-positive bar plus histogram of positive premiums                  |Whether glass coverage is common.                                                            |\n|legal_protection_premium    |Optional premium                 |Zero-versus-positive bar plus histogram of positive premiums                  |Whether legal protection is commonly purchased.                                              |\n|occupants_premium           |Optional premium                 |Zero-versus-positive bar plus histogram of positive premiums                  |Whether occupant injury coverage is common.                                                  |\n|total_claims                |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Usually many policies have 0 claims.                                                         |\n|liability_claims            |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Number of liability claims.                                                                  |\n|liability_property_claims   |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Claims involving third-party property damage.                                                |\n|liability_injury_claims     |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Injury-related liability claims.                                                             |\n|property_claims             |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Property damage claim frequency.                                                             |\n|theft_claims                |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Theft claim frequency.                                                                       |\n|fire_claims                 |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Fire claim frequency.                                                                        |\n|glass_claims                |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Glass claim frequency.                                                                       |\n|legal_protection_claims     |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Legal protection claim frequency.                                                            |\n|occupants_claims            |Count                            |Bar chart of claim-count values plus 0 versus 1+ claims                       |Occupant injury claim frequency.                                                             |\n|total_incurred              |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Claim cost severity and extreme losses.                                                      |\n|liability_incurred          |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Cost of liability claims.                                                                    |\n|liability_property_incurred |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Cost of liability property damage.                                                           |\n|liability_injury_incurred   |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Injury claim costs, likely very skewed.                                                      |\n|property_incurred           |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Property damage claim costs.                                                                 |\n|theft_incurred              |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Theft claim costs.                                                                           |\n|fire_incurred               |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Fire claim costs.                                                                            |\n|glass_incurred              |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Glass claim costs.                                                                           |\n|legal_protection_incurred   |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Legal protection claim costs.                                                                |\n|occupants_incurred          |Numerical money                  |Zero-versus-positive bar; log-scale histogram and boxplot for positive values |Occupant injury claim costs.                                                                 |\n|total_exposure              |Numerical                        |Histogram + boxplot                                                           |Full-year policies versus partial-year policies; check values above 1.                       |\n|liability_exposure          |Numerical                        |Histogram + boxplot                                                           |Exposure time for liability coverage.                                                        |\n\n\n:::\n:::\n\n\n::: observation-box\n**Observations**\n\n-   The visual choice is now tied to the analytical type of each column, rather than only to its stored R class.\n-   Optional coverages and incurred-loss fields are separated into zero-versus-positive and positive-value severity views to avoid zero inflation hiding the useful distribution.\n-   `licence_years_held` is added as a derived check because it is easier to interpret than the raw licence year alone.\n:::\n\n### Reusable profiling functions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat_profile_value <- function(x, var = NULL) {\n  if (length(x) == 0 || is.na(x) || !is.finite(x)) return(\"NA\")\n  if (!is.null(var) && str_detect(var, \"premium|incurred|vehicle_value|profit|severity\")) {\n    return(money(x))\n  }\n  comma(round(x, 2))\n}\n\nnumeric_profile_summary <- function(df, var) {\n  x <- suppressWarnings(as.numeric(df[[var]]))\n  finite_x <- x[is.finite(x)]\n  tibble(\n    metric = c(\"Missing records\", \"Missing share\", \"Zero share\", \"Minimum\", \"Median\", \"Mean\", \"95th percentile\", \"Maximum\"),\n    value = c(\n      comma(sum(is.na(x))),\n      pct(mean(is.na(x))),\n      if (length(finite_x) == 0) \"NA\" else pct(mean(finite_x == 0)),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(min(finite_x), var),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(median(finite_x), var),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(mean(finite_x), var),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(quantile(finite_x, 0.95, na.rm = TRUE), var),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(max(finite_x), var)\n    )\n  )\n}\n\ncategorical_profile_summary <- function(df, var) {\n  x <- df[[var]]\n  non_missing <- x[!is.na(x)]\n  tab <- sort(table(non_missing), decreasing = TRUE)\n  tibble(\n    metric = c(\"Missing records\", \"Missing share\", \"Distinct non-missing values\", \"Top category\", \"Top-category share\"),\n    value = c(\n      comma(sum(is.na(x))),\n      pct(mean(is.na(x))),\n      comma(n_distinct(x, na.rm = TRUE)),\n      if (length(tab) == 0) \"NA\" else names(tab)[1],\n      if (length(tab) == 0) \"NA\" else pct(as.numeric(tab[1]) / length(non_missing))\n    )\n  )\n}\n\nid_profile_summary <- function(df, var) {\n  x <- df[[var]]\n  tibble(\n    metric = c(\"Policy-year records\", \"Unique IDs\", \"Duplicate ID records\", \"Missing ID records\"),\n    value = c(\n      comma(length(x)),\n      comma(n_distinct(x, na.rm = TRUE)),\n      comma(length(x) - n_distinct(x, na.rm = TRUE)),\n      comma(sum(is.na(x)))\n    )\n  )\n}\n\nprofile_summary <- function(df, var, family) {\n  if (family == \"id\") return(id_profile_summary(df, var))\n  if (family %in% c(\"categorical\", \"ordinal\", \"year\")) return(categorical_profile_summary(df, var))\n  numeric_profile_summary(df, var)\n}\n\nempty_plot <- function(title, message) {\n  ggplot() +\n    annotate(\"text\", x = 0, y = 0, label = message) +\n    theme_void() +\n    labs(title = title)\n}\n\nhist_box_visual <- function(df, var, title = NULL, subtitle = NULL, positive_only = FALSE, log_scale = FALSE) {\n  plot_df <- tibble(value = suppressWarnings(as.numeric(df[[var]]))) |>\n    filter(is.finite(value))\n  if (positive_only) plot_df <- plot_df |> filter(value > 0)\n\n  if (nrow(plot_df) == 0) {\n    return(empty_plot(paste(\"Distribution of\", var), \"No finite values available\"))\n  }\n\n  if (!log_scale) {\n    lower <- quantile(plot_df$value, 0.01, na.rm = TRUE)\n    upper <- quantile(plot_df$value, 0.99, na.rm = TRUE)\n    plot_df <- plot_df |>\n      mutate(value_plot = pmin(pmax(value, lower), upper))\n    plot_subtitle <- coalesce(subtitle, \"Histogram and boxplot; values are capped at the 1st and 99th percentiles for readability only.\")\n  } else {\n    plot_df <- plot_df |> mutate(value_plot = value)\n    plot_subtitle <- coalesce(subtitle, \"Positive values only; x-axis is log-scaled to reveal skewed claim-cost severity.\")\n  }\n\n  x_labeller <- if (str_detect(var, \"premium|incurred|vehicle_value|profit|severity\")) money else comma\n\n  hist <- ggplot(plot_df, aes(x = value_plot)) +\n    geom_histogram(bins = 35, colour = \"white\", fill = \"#2c7fb8\") +\n    labs(x = var, y = \"Number of records\") +\n    scale_x_continuous(labels = x_labeller)\n\n  box <- ggplot(plot_df, aes(x = value_plot, y = \"\")) +\n    geom_boxplot(fill = \"#a6bddb\", colour = \"#045a8d\", outlier.alpha = 0.35) +\n    labs(x = var, y = NULL) +\n    scale_x_continuous(labels = x_labeller)\n\n  if (log_scale) {\n    hist <- hist + scale_x_log10(labels = x_labeller)\n    box <- box + scale_x_log10(labels = x_labeller)\n  }\n\n  hist / box +\n    plot_layout(heights = c(3, 1)) +\n    plot_annotation(\n      title = coalesce(title, paste(\"Distribution of\", var)),\n      subtitle = plot_subtitle\n    )\n}\n\nzero_positive_bar <- function(df, var, positive_label = \"Positive\") {\n  fill_values <- c(\"#bdbdbd\", \"#2c7fb8\", \"#fdae6b\", \"#756bb1\")\n  names(fill_values) <- c(\"Zero\", positive_label, \"Negative\", \"Missing\")\n\n  tibble(value = suppressWarnings(as.numeric(df[[var]]))) |>\n    mutate(status = case_when(\n      is.na(value) ~ \"Missing\",\n      value > 0 ~ positive_label,\n      value == 0 ~ \"Zero\",\n      TRUE ~ \"Negative\"\n    )) |>\n    count(status, name = \"n\") |>\n    mutate(\n      share = n / sum(n),\n      status = factor(status, levels = c(\"Zero\", positive_label, \"Negative\", \"Missing\"))\n    ) |>\n    ggplot(aes(x = status, y = share, fill = status)) +\n    geom_col(show.legend = FALSE) +\n    geom_text(aes(label = percent(share, accuracy = 0.1)), vjust = -0.25, size = 3.5) +\n    scale_y_continuous(labels = percent, limits = c(0, NA)) +\n    scale_fill_manual(values = fill_values) +\n    labs(\n      title = paste(\"Zero versus positive\", var),\n      x = NULL,\n      y = \"Share of records\"\n    )\n}\n\noptional_premium_visual <- function(df, var) {\n  zero_positive_bar(df, var, positive_label = \"Positive premium\") /\n    hist_box_visual(\n      df, var,\n      title = paste(\"Positive premium distribution for\", var),\n      subtitle = \"Positive premium values only; zero premiums are shown separately above.\",\n      positive_only = TRUE,\n      log_scale = FALSE\n    ) +\n    plot_layout(heights = c(1, 2.4))\n}\n\nincurred_visual <- function(df, var) {\n  zero_positive_bar(df, var, positive_label = \"Positive incurred\") /\n    hist_box_visual(\n      df, var,\n      title = paste(\"Positive incurred-cost distribution for\", var),\n      positive_only = TRUE,\n      log_scale = TRUE\n    ) +\n    plot_layout(heights = c(1, 2.4))\n}\n\nclaim_count_visual <- function(df, var) {\n  count_plot <- tibble(value = suppressWarnings(as.numeric(df[[var]]))) |>\n    mutate(claim_count = if_else(is.na(value), \"Missing\", as.character(value))) |>\n    count(claim_count, name = \"n\") |>\n    mutate(claim_count = fct_reorder(claim_count, suppressWarnings(as.numeric(claim_count)), .na_rm = TRUE)) |>\n    ggplot(aes(x = claim_count, y = n)) +\n    geom_col(fill = \"#2c7fb8\") +\n    labs(\n      title = paste(\"Claim-count distribution for\", var),\n      x = \"Claim count\",\n      y = \"Number of records\"\n    )\n\n  flag_plot <- tibble(value = suppressWarnings(as.numeric(df[[var]]))) |>\n    mutate(status = case_when(\n      is.na(value) ~ \"Missing\",\n      value == 0 ~ \"0 claims\",\n      value > 0 ~ \"1 or more claims\",\n      TRUE ~ \"Negative\"\n    )) |>\n    count(status, name = \"n\") |>\n    mutate(\n      share = n / sum(n),\n      status = factor(status, levels = c(\"0 claims\", \"1 or more claims\", \"Negative\", \"Missing\"))\n    ) |>\n    ggplot(aes(x = status, y = share, fill = status)) +\n    geom_col(show.legend = FALSE) +\n    geom_text(aes(label = percent(share, accuracy = 0.1)), vjust = -0.25, size = 3.5) +\n    scale_y_continuous(labels = percent, limits = c(0, NA)) +\n    scale_fill_manual(values = c(\"0 claims\" = \"#bdbdbd\", \"1 or more claims\" = \"#2c7fb8\", \"Negative\" = \"#fdae6b\", \"Missing\" = \"#756bb1\")) +\n    labs(\n      title = paste(\"Claim occurrence for\", var),\n      x = NULL,\n      y = \"Share of records\"\n    )\n\n  count_plot / flag_plot + plot_layout(heights = c(1.4, 1))\n}\n\nyear_visual <- function(df, var) {\n  df |>\n    transmute(year_value = fct_na_value_to_level(as.factor(.data[[var]]), level = \"Missing\")) |>\n    count(year_value, name = \"n\") |>\n    ggplot(aes(x = year_value, y = n, group = 1)) +\n    geom_col(fill = \"#756bb1\", alpha = 0.75) +\n    geom_line(colour = \"#d95f0e\", linewidth = 1) +\n    geom_point(colour = \"#d95f0e\", size = 2) +\n    labs(\n      title = \"Policy-year record counts by year\",\n      x = \"Year\",\n      y = \"Number of records\"\n    )\n}\n\ncategorical_visual <- function(df, var, family = \"categorical\", top_n = NA_real_) {\n  plot_df <- df |>\n    transmute(category = fct_na_value_to_level(as.factor(.data[[var]]), level = \"Missing\")) |>\n    count(category, name = \"n\")\n\n  if (family == \"ordinal\" && var == \"bonus_score\") {\n    preferred_levels <- c(\"bad\", \"Bad\", \"neutral\", \"Neutral\", \"good\", \"Good\")\n    level_order <- c(intersect(preferred_levels, as.character(plot_df$category)), setdiff(as.character(plot_df$category), preferred_levels))\n    plot_df <- plot_df |> mutate(category = factor(as.character(category), levels = level_order))\n  } else {\n    if (!is.na(top_n)) {\n      plot_df <- plot_df |>\n        mutate(category = fct_lump_n(category, n = top_n, w = n, other_level = \"Other\")) |>\n        group_by(category) |>\n        summarise(n = sum(n), .groups = \"drop\")\n    }\n    plot_df <- plot_df |> mutate(category = fct_reorder(category, n))\n  }\n\n  plot_df |>\n    mutate(share = n / sum(n)) |>\n    ggplot(aes(x = category, y = share)) +\n    geom_col(fill = \"#756bb1\") +\n    coord_flip() +\n    scale_y_continuous(labels = percent) +\n    labs(\n      title = paste(\"Composition of\", var),\n      subtitle = if (!is.na(top_n)) paste(\"Top\", top_n, \"categories retained; remaining categories grouped as Other.\") else \"Bars show share of policy-year records.\",\n      x = NULL,\n      y = \"Share of records\"\n    )\n}\n\nmake_profile_visual <- function(df, spec_row) {\n  var <- spec_row$variable\n  family <- spec_row$visual_family\n  top_n <- spec_row$top_n\n\n  if (family == \"id\") return(NULL)\n  if (family == \"year\") return(year_visual(df, var))\n  if (family %in% c(\"categorical\", \"ordinal\")) return(categorical_visual(df, var, family, top_n))\n  if (family == \"discrete\") return(categorical_visual(df, var, \"categorical\", NA_real_))\n  if (family == \"optional_premium\") return(optional_premium_visual(df, var))\n  if (family == \"incurred\") return(incurred_visual(df, var))\n  if (family == \"claim_count\") return(claim_count_visual(df, var))\n  hist_box_visual(df, var)\n}\n\nprofile_insights <- function(df, spec_row) {\n  var <- spec_row$variable\n  family <- spec_row$visual_family\n  x <- df[[var]]\n  bullets <- c(paste0(\"Recommended check: \", spec_row$what_to_look_for))\n\n  if (family == \"id\") {\n    duplicate_records <- length(x) - n_distinct(x, na.rm = TRUE)\n    bullets <- c(\n      bullets,\n      paste0(\"There are \", comma(n_distinct(x, na.rm = TRUE)), \" unique IDs across \", comma(length(x)), \" policy-year records.\"),\n      paste0(\"Duplicate ID records equal \", comma(duplicate_records), \"; this is expected if an insured appears in more than one year, but the ID should not be modelled as a continuous value.\")\n    )\n    return(paste0(\"- \", bullets, collapse = \"\\n\") |> paste0(\"\\n\"))\n  }\n\n  if (family %in% c(\"categorical\", \"ordinal\", \"year\", \"discrete\")) {\n    tab <- sort(table(x, useNA = \"no\"), decreasing = TRUE)\n    missing_share <- mean(is.na(x))\n    distinct_values <- n_distinct(x, na.rm = TRUE)\n    if (missing_share > 0) bullets <- c(bullets, paste0(\"Missing records account for \", pct(missing_share), \" and are shown explicitly where relevant.\"))\n    if (distinct_values > 20) bullets <- c(bullets, paste0(\"The variable has \", distinct_values, \" distinct values, so top-N grouping protects readability.\"))\n    if (length(tab) > 0) bullets <- c(bullets, paste0(\"The largest category is `\", names(tab)[1], \"` with \", pct(as.numeric(tab[1]) / sum(tab)), \" of non-missing records.\"))\n  } else {\n    num_x <- suppressWarnings(as.numeric(x))\n    finite_x <- num_x[is.finite(num_x)]\n    if (length(finite_x) == 0) bullets <- c(bullets, \"No finite values are available for interpretation.\")\n    if (length(finite_x) > 0) {\n      missing_share <- mean(is.na(num_x))\n      zero_share <- mean(finite_x == 0)\n      median_value <- median(finite_x)\n      mean_value <- mean(finite_x)\n      p95_value <- quantile(finite_x, 0.95, na.rm = TRUE)\n      max_value <- max(finite_x)\n      if (missing_share > 0) bullets <- c(bullets, paste0(\"Missing records account for \", pct(missing_share), \".\"))\n      if (zero_share > 0.50) bullets <- c(bullets, paste0(\"The variable is zero-inflated: \", pct(zero_share), \" of finite records are zero.\"))\n      if (median_value == 0 && p95_value > 0) {\n        bullets <- c(bullets, \"The median is zero but the upper tail is positive, so the positive-value visual is more informative than a standard histogram alone.\")\n      } else if (abs(mean_value) > abs(median_value) * 2 && p95_value > median_value) {\n        bullets <- c(bullets, \"The mean is much larger than the median, indicating right skew and possible expensive outliers.\")\n      }\n      bullets <- c(bullets, paste0(\"The 95th percentile is \", format_profile_value(p95_value, var), \" and the maximum is \", format_profile_value(max_value, var), \".\"))\n    }\n  }\n\n  if (length(bullets) > 3) bullets <- bullets[1:3]\n  paste0(\"- \", bullets, collapse = \"\\n\") |> paste0(\"\\n\")\n}\n```\n:::\n\n\n### Column-by-column profiles\n\n\n```{.r .cell-code}\nfor (i in seq_len(nrow(profile_spec))) {\n  spec_row <- profile_spec[i, ]\n  var <- spec_row$variable\n  family <- spec_row$visual_family\n\n  cat(\"\\n\\n#### `\", var, \"`\\n\\n\", sep = \"\")\n  cat(\"**Variable type:** \", spec_row$variable_type, \"  \\n\", sep = \"\")\n  cat(\"**Best univariate visual:** \", spec_row$best_univariate_visual, \"\\n\\n\", sep = \"\")\n\n  print(profile_summary(motor_profile, var, family) |> kable())\n  cat(\"\\n\\n\")\n\n  plot_obj <- make_profile_visual(motor_profile, spec_row)\n  if (is.null(plot_obj)) {\n    cat(\"No normal numeric plot is shown because this is an identifier field.\\n\\n\")\n  } else {\n    print(plot_obj)\n    cat(\"\\n\\n\")\n  }\n\n  cat(\"::: {.observation-box}\\n\")\n  cat(\"**Insights**\\n\\n\")\n  cat(profile_insights(motor_profile, spec_row))\n  cat(\":::\\n\\n\")\n}\n```\n\n\n\n#### `insured_id`\n\n**Variable type:** ID  \n**Best univariate visual:** Uniqueness count and duplicate count\n\n\n\n|metric               |value   |\n|:--------------------|:-------|\n|Policy-year records  |354,140 |\n|Unique IDs           |185,678 |\n|Duplicate ID records |168,462 |\n|Missing ID records   |0       |\n\n\nNo normal numeric plot is shown because this is an identifier field.\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: How many unique policies or customers exist; do not treat this as a normal numeric variable.\n- There are 185,678 unique IDs across 354,140 policy-year records.\n- Duplicate ID records equal 168,462; this is expected if an insured appears in more than one year, but the ID should not be modelled as a continuous value.\n:::\n\n\n\n#### `year`\n\n**Variable type:** Time / ordinal categorical  \n**Best univariate visual:** Bar chart plus line of record counts by year\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |3     |\n|Top category                |2024  |\n|Top-category share          |47.5% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-1.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Which years have more policies.\n- The largest category is `2024` with 47.5% of non-missing records.\n:::\n\n\n\n#### `policy_type`\n\n**Variable type:** Categorical  \n**Best univariate visual:** Bar chart / count plot\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |5     |\n|Top category                |CC    |\n|Top-category share          |57.8% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-2.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Most common insurance coverage type.\n- The largest category is `CC` with 57.8% of non-missing records.\n:::\n\n\n\n#### `policy_status`\n\n**Variable type:** Categorical  \n**Best univariate visual:** Bar chart\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |2     |\n|Top category                |A     |\n|Top-category share          |89.2% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-3.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Active versus cancelled policies.\n- The largest category is `A` with 89.2% of non-missing records.\n:::\n\n\n\n#### `business_type`\n\n**Variable type:** Categorical  \n**Best univariate visual:** Bar chart\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |2     |\n|Top category                |NB    |\n|Top-category share          |69.3% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-4.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: New business versus portfolio policies.\n- The largest category is `NB` with 69.3% of non-missing records.\n:::\n\n\n\n#### `payment_frequency`\n\n**Variable type:** Categorical  \n**Best univariate visual:** Bar chart\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |3     |\n|Top category                |A     |\n|Top-category share          |81.3% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-5.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Annual, semiannual, or quarterly payment patterns.\n- The largest category is `A` with 81.3% of non-missing records.\n:::\n\n\n\n#### `bonus_score`\n\n**Variable type:** Ordinal categorical  \n**Best univariate visual:** Ordered bar chart\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |3     |\n|Top category                |G     |\n|Top-category share          |96.4% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-6.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Distribution of good, neutral, and bad claim history.\n- The largest category is `G` with 96.4% of non-missing records.\n:::\n\n\n\n#### `driver_age`\n\n**Variable type:** Numerical  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |18    |\n|Median          |48    |\n|Mean            |49    |\n|95th percentile |69    |\n|Maximum         |90    |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-7.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Age distribution and young or old driver outliers.\n- The 95th percentile is 69 and the maximum is 90.\n:::\n\n\n\n#### `vehicle_age`\n\n**Variable type:** Numerical  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |2     |\n|Missing share   |0.0%  |\n|Zero share      |0.1%  |\n|Minimum         |0     |\n|Median          |25    |\n|Mean            |26    |\n|95th percentile |46    |\n|Maximum         |68    |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-8.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Whether cars are mostly new or old.\n- Missing records account for 0.0%.\n- The 95th percentile is 46 and the maximum is 68.\n:::\n\n\n\n#### `age_driving_licence`\n\n**Variable type:** Year variable  \n**Best univariate visual:** Histogram or bar chart by licence year\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |2     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |0     |\n|Median          |20    |\n|Mean            |23    |\n|95th percentile |37    |\n|Maximum         |80    |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-9.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: When drivers got their licence.\n- Missing records account for 0.0%.\n- The 95th percentile is 37 and the maximum is 80.\n:::\n\n\n\n#### `licence_years_held`\n\n**Variable type:** Derived numerical  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |2     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |1,944 |\n|Median          |2,003 |\n|Mean            |2,000 |\n|95th percentile |2,006 |\n|Maximum         |2,024 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-10.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Approximate driving experience, calculated as year minus licence year.\n- Missing records account for 0.0%.\n- The 95th percentile is 2,006 and the maximum is 2,024.\n:::\n\n\n\n#### `fuel_type`\n\n**Variable type:** Categorical  \n**Best univariate visual:** Bar chart\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |1,287 |\n|Missing share               |0.4%  |\n|Distinct non-missing values |2     |\n|Top category                |D     |\n|Top-category share          |64.2% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-11.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Diesel versus gasoline split.\n- Missing records account for 0.4% and are shown explicitly where relevant.\n- The largest category is `D` with 64.2% of non-missing records.\n:::\n\n\n\n#### `vehicle_value`\n\n**Variable type:** Numerical money/value  \n**Best univariate visual:** Histogram + boxplot plus missing-value check\n\n\n\n|metric          |value    |\n|:---------------|:--------|\n|Missing records |513      |\n|Missing share   |0.1%     |\n|Zero share      |0.0%     |\n|Minimum         |€1,630   |\n|Median          |€24,730  |\n|Mean            |€26,977  |\n|95th percentile |€49,361  |\n|Maximum         |€374,034 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-12.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Car value distribution, missing values, and expensive outliers.\n- Missing records account for 0.1%.\n- The 95th percentile is €49,361 and the maximum is €374,034.\n:::\n\n\n\n#### `seats`\n\n**Variable type:** Discrete numerical / categorical  \n**Best univariate visual:** Bar chart\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |2     |\n|Median          |5     |\n|Mean            |5     |\n|95th percentile |7     |\n|Maximum         |9     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-13.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Common seat numbers, for example 4, 5, or 7.\n- The largest category is `5` with 84.9% of non-missing records.\n:::\n\n\n\n#### `power_to_weight_ratio`\n\n**Variable type:** Numerical  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |0     |\n|Median          |12    |\n|Mean            |12    |\n|95th percentile |17    |\n|Maximum         |65    |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-14.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Vehicle performance distribution and outliers.\n- The 95th percentile is 17 and the maximum is 65.\n:::\n\n\n\n#### `vehicle_brand`\n\n**Variable type:** High-cardinality categorical  \n**Best univariate visual:** Horizontal bar chart of top 20 brands\n\n\n\n|metric                      |value   |\n|:---------------------------|:-------|\n|Missing records             |0       |\n|Missing share               |0.0%    |\n|Distinct non-missing values |68      |\n|Top category                |RENAULT |\n|Top-category share          |9.7%    |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-15.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Most common brands; rare brands are grouped as Other.\n- The variable has 68 distinct values, so top-N grouping protects readability.\n- The largest category is `RENAULT` with 9.7% of non-missing records.\n:::\n\n\n\n#### `municipality_type`\n\n**Variable type:** Categorical  \n**Best univariate visual:** Bar chart\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |3     |\n|Top category                |I     |\n|Top-category share          |64.6% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-16.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Inland, coastal, and island distribution.\n- The largest category is `I` with 64.6% of non-missing records.\n:::\n\n\n\n#### `circulation_area`\n\n**Variable type:** Categorical  \n**Best univariate visual:** Bar chart\n\n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |2     |\n|Top category                |U     |\n|Top-category share          |53.8% |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-17.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Urban versus rural distribution.\n- The largest category is `U` with 53.8% of non-missing records.\n:::\n\n\n\n#### `total_premium`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |0.0%   |\n|Minimum         |€0     |\n|Median          |€258   |\n|Mean            |€297   |\n|95th percentile |€705   |\n|Maximum         |€5,108 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-18.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Overall price distribution and expensive policies.\n- The 95th percentile is €705 and the maximum is €5,108.\n:::\n\n\n\n#### `liability_premium`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |0.0%   |\n|Minimum         |€0     |\n|Median          |€166   |\n|Mean            |€181   |\n|95th percentile |€400   |\n|Maximum         |€2,321 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-19.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Cost of third-party liability coverage.\n- The 95th percentile is €400 and the maximum is €2,321.\n:::\n\n\n\n#### `property_damage_premium`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |69.1%  |\n|Minimum         |€0     |\n|Median          |€0     |\n|Mean            |€74    |\n|95th percentile |€377   |\n|Maximum         |€3,737 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-20.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Distribution of property damage premium.\n- The variable is zero-inflated: 69.1% of finite records are zero.\n- The median is zero but the upper tail is positive, so the positive-value visual is more informative than a standard histogram alone.\n:::\n\n\n\n#### `theft_premium`\n\n**Variable type:** Optional premium  \n**Best univariate visual:** Zero-versus-positive bar plus histogram of positive premiums\n\n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |11.9%  |\n|Minimum         |€0     |\n|Median          |€6     |\n|Mean            |€11    |\n|95th percentile |€39    |\n|Maximum         |€1,047 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-21.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Whether theft coverage is commonly purchased.\n- The 95th percentile is €39 and the maximum is €1,047.\n:::\n\n\n\n#### `fire_premium`\n\n**Variable type:** Optional premium  \n**Best univariate visual:** Zero-versus-positive bar plus histogram of positive premiums\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |11.9% |\n|Minimum         |€0    |\n|Median          |€1    |\n|Mean            |€2    |\n|95th percentile |€5    |\n|Maximum         |€72   |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-22.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Whether fire coverage is commonly purchased.\n- The 95th percentile is €5 and the maximum is €72.\n:::\n\n\n\n#### `glass_premium`\n\n**Variable type:** Optional premium  \n**Best univariate visual:** Zero-versus-positive bar plus histogram of positive premiums\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |1.6%  |\n|Minimum         |€0    |\n|Median          |€15   |\n|Mean            |€19   |\n|95th percentile |€52   |\n|Maximum         |€388  |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-23.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Whether glass coverage is common.\n- The 95th percentile is €52 and the maximum is €388.\n:::\n\n\n\n#### `legal_protection_premium`\n\n**Variable type:** Optional premium  \n**Best univariate visual:** Zero-versus-positive bar plus histogram of positive premiums\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |€0    |\n|Median          |€7    |\n|Mean            |€8    |\n|95th percentile |€22   |\n|Maximum         |€175  |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-24.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Whether legal protection is commonly purchased.\n- The 95th percentile is €22 and the maximum is €175.\n:::\n\n\n\n#### `occupants_premium`\n\n**Variable type:** Optional premium  \n**Best univariate visual:** Zero-versus-positive bar plus histogram of positive premiums\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |€0    |\n|Median          |€2    |\n|Mean            |€2    |\n|95th percentile |€5    |\n|Maximum         |€69   |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-25.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Whether occupant injury coverage is common.\n- The 95th percentile is €5 and the maximum is €69.\n:::\n\n\n\n#### `total_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |85.7% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |1     |\n|Maximum         |18    |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-26.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Usually many policies have 0 claims.\n- The variable is zero-inflated: 85.7% of finite records are zero.\n- The median is zero but the upper tail is positive, so the positive-value visual is more informative than a standard histogram alone.\n:::\n\n\n\n#### `liability_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |91.3% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |1     |\n|Maximum         |8     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-27.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Number of liability claims.\n- The variable is zero-inflated: 91.3% of finite records are zero.\n- The median is zero but the upper tail is positive, so the positive-value visual is more informative than a standard histogram alone.\n:::\n\n\n\n#### `liability_property_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |91.5% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |1     |\n|Maximum         |8     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-28.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Claims involving third-party property damage.\n- The variable is zero-inflated: 91.5% of finite records are zero.\n- The median is zero but the upper tail is positive, so the positive-value visual is more informative than a standard histogram alone.\n:::\n\n\n\n#### `liability_injury_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |98.7% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |0     |\n|Maximum         |3     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-29.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Injury-related liability claims.\n- The variable is zero-inflated: 98.7% of finite records are zero.\n- The 95th percentile is 0 and the maximum is 3.\n:::\n\n\n\n#### `property_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |96.5% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |0     |\n|Maximum         |15    |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-30.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Property damage claim frequency.\n- The variable is zero-inflated: 96.5% of finite records are zero.\n- The 95th percentile is 0 and the maximum is 15.\n:::\n\n\n\n#### `theft_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |99.5% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |0     |\n|Maximum         |2     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-31.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Theft claim frequency.\n- The variable is zero-inflated: 99.5% of finite records are zero.\n- The 95th percentile is 0 and the maximum is 2.\n:::\n\n\n\n#### `fire_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |100.0% |\n|Minimum         |0      |\n|Median          |0      |\n|Mean            |0      |\n|95th percentile |0      |\n|Maximum         |1      |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-32.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Fire claim frequency.\n- The variable is zero-inflated: 100.0% of finite records are zero.\n- The 95th percentile is 0 and the maximum is 1.\n:::\n\n\n\n#### `glass_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |96.9% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |0     |\n|Maximum         |3     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-33.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Glass claim frequency.\n- The variable is zero-inflated: 96.9% of finite records are zero.\n- The 95th percentile is 0 and the maximum is 3.\n:::\n\n\n\n#### `legal_protection_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |99.0% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |0     |\n|Maximum         |2     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-34.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Legal protection claim frequency.\n- The variable is zero-inflated: 99.0% of finite records are zero.\n- The 95th percentile is 0 and the maximum is 2.\n:::\n\n\n\n#### `occupants_claims`\n\n**Variable type:** Count  \n**Best univariate visual:** Bar chart of claim-count values plus 0 versus 1+ claims\n\n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |100.0% |\n|Minimum         |0      |\n|Median          |0      |\n|Mean            |0      |\n|95th percentile |0      |\n|Maximum         |1      |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-35.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Occupant injury claim frequency.\n- The variable is zero-inflated: 100.0% of finite records are zero.\n- The 95th percentile is 0 and the maximum is 1.\n:::\n\n\n\n#### `total_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value    |\n|:---------------|:--------|\n|Missing records |0        |\n|Missing share   |0.0%     |\n|Zero share      |88.1%    |\n|Minimum         |€0       |\n|Median          |€0       |\n|Mean            |€209     |\n|95th percentile |€1,055   |\n|Maximum         |€571,128 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-36.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Claim cost severity and extreme losses.\n- The variable is zero-inflated: 88.1% of finite records are zero.\n- The median is zero but the upper tail is positive, so the positive-value visual is more informative than a standard histogram alone.\n:::\n\n\n\n#### `liability_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value    |\n|:---------------|:--------|\n|Missing records |0        |\n|Missing share   |0.0%     |\n|Zero share      |94.1%    |\n|Minimum         |€0       |\n|Median          |€0       |\n|Mean            |€134     |\n|95th percentile |€528     |\n|Maximum         |€561,760 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-37.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Cost of liability claims.\n- The variable is zero-inflated: 94.1% of finite records are zero.\n- The median is zero but the upper tail is positive, so the positive-value visual is more informative than a standard histogram alone.\n:::\n\n\n\n#### `liability_property_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value   |\n|:---------------|:-------|\n|Missing records |0       |\n|Missing share   |0.0%    |\n|Zero share      |94.5%   |\n|Minimum         |€0      |\n|Median          |€0      |\n|Mean            |€66     |\n|95th percentile |€213    |\n|Maximum         |€34,554 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-38.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Cost of liability property damage.\n- The variable is zero-inflated: 94.5% of finite records are zero.\n- The median is zero but the upper tail is positive, so the positive-value visual is more informative than a standard histogram alone.\n:::\n\n\n\n#### `liability_injury_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value    |\n|:---------------|:--------|\n|Missing records |0        |\n|Missing share   |0.0%     |\n|Zero share      |98.7%    |\n|Minimum         |€0       |\n|Median          |€0       |\n|Mean            |€68      |\n|95th percentile |€0       |\n|Maximum         |€560,026 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-39.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Injury claim costs, likely very skewed.\n- The variable is zero-inflated: 98.7% of finite records are zero.\n- The 95th percentile is €0 and the maximum is €560,026.\n:::\n\n\n\n#### `property_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value   |\n|:---------------|:-------|\n|Missing records |0       |\n|Missing share   |0.0%    |\n|Zero share      |96.5%   |\n|Minimum         |€0      |\n|Median          |€0      |\n|Mean            |€53     |\n|95th percentile |€0      |\n|Maximum         |€27,542 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-40.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Property damage claim costs.\n- The variable is zero-inflated: 96.5% of finite records are zero.\n- The 95th percentile is €0 and the maximum is €27,542.\n:::\n\n\n\n#### `theft_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value   |\n|:---------------|:-------|\n|Missing records |0       |\n|Missing share   |0.0%    |\n|Zero share      |99.5%   |\n|Minimum         |€0      |\n|Median          |€0      |\n|Mean            |€5      |\n|95th percentile |€0      |\n|Maximum         |€40,325 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-41.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Theft claim costs.\n- The variable is zero-inflated: 99.5% of finite records are zero.\n- The 95th percentile is €0 and the maximum is €40,325.\n:::\n\n\n\n#### `fire_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value   |\n|:---------------|:-------|\n|Missing records |0       |\n|Missing share   |0.0%    |\n|Zero share      |100.0%  |\n|Minimum         |€0      |\n|Median          |€0      |\n|Mean            |€1      |\n|95th percentile |€0      |\n|Maximum         |€28,267 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-42.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Fire claim costs.\n- The variable is zero-inflated: 100.0% of finite records are zero.\n- The 95th percentile is €0 and the maximum is €28,267.\n:::\n\n\n\n#### `glass_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |96.9%  |\n|Minimum         |€0     |\n|Median          |€0     |\n|Mean            |€13    |\n|95th percentile |€0     |\n|Maximum         |€4,533 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-43.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Glass claim costs.\n- The variable is zero-inflated: 96.9% of finite records are zero.\n- The 95th percentile is €0 and the maximum is €4,533.\n:::\n\n\n\n#### `legal_protection_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |99.1%  |\n|Minimum         |€0     |\n|Median          |€0     |\n|Mean            |€3     |\n|95th percentile |€0     |\n|Maximum         |€9,890 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-44.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Legal protection claim costs.\n- The variable is zero-inflated: 99.1% of finite records are zero.\n- The 95th percentile is €0 and the maximum is €9,890.\n:::\n\n\n\n#### `occupants_incurred`\n\n**Variable type:** Numerical money  \n**Best univariate visual:** Zero-versus-positive bar; log-scale histogram and boxplot for positive values\n\n\n\n|metric          |value   |\n|:---------------|:-------|\n|Missing records |0       |\n|Missing share   |0.0%    |\n|Zero share      |100.0%  |\n|Minimum         |€0      |\n|Median          |€0      |\n|Mean            |€1      |\n|95th percentile |€0      |\n|Maximum         |€69,000 |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-45.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Occupant injury claim costs.\n- The variable is zero-inflated: 100.0% of finite records are zero.\n- The 95th percentile is €0 and the maximum is €69,000.\n:::\n\n\n\n#### `total_exposure`\n\n**Variable type:** Numerical  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |0     |\n|Median          |1     |\n|Mean            |1     |\n|95th percentile |1     |\n|Maximum         |1     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-46.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Full-year policies versus partial-year policies; check values above 1.\n- The 95th percentile is 1 and the maximum is 1.\n:::\n\n\n\n#### `liability_exposure`\n\n**Variable type:** Numerical  \n**Best univariate visual:** Histogram + boxplot\n\n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |0     |\n|Median          |1     |\n|Mean            |1     |\n|95th percentile |1     |\n|Maximum         |1     |\n\n\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/univariate-column-profiles-47.png){width=864}\n\n::: {.observation-box}\n**Insights**\n\n- Recommended check: Exposure time for liability coverage.\n- The 95th percentile is 1 and the maximum is 1.\n:::\n\n## Task 2: Bivariate visual analytics and validation\n\nBivariate analysis compares profitability and volatility across time and major risk-related segments. The main profitability visual is aggregate loss ratio; the main volatility visuals are claim frequency, high-loss rate, and spread of capped individual loss ratios.\n\n### Temporal trend: profitability worsens in 2024\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyearly <- portfolio_summary(motor, year)\nkable(yearly, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|year | records|  exposure|  premium| incurred| claims|   profit| high_loss_rate| p95_loss_ratio| loss_ratio| claim_frequency| avg_premium| avg_severity|\n|:----|-------:|---------:|--------:|--------:|------:|--------:|--------------:|--------------:|----------:|---------------:|-----------:|------------:|\n|2022 |   67172|  41912.50| 18697928| 12270105|  12665|  6427823|          0.080|          2.419|      0.656|           0.302|     446.118|      968.820|\n|2023 |  118835|  82399.04| 35344308| 23488354|  25158| 11855954|          0.087|          2.744|      0.665|           0.305|     428.941|      933.634|\n|2024 |  168133| 126014.36| 51037433| 38106351|  39276| 12931082|          0.097|          3.205|      0.747|           0.312|     405.013|      970.220|\n\n\n:::\n:::\n\n\n-   The year-level table summarises exposure, premium, incurred loss, profit, and loss ratio.\n-   It provides the numeric baseline for the temporal trend plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrend_amount <- yearly |>\n  select(year, Premium = premium, Incurred = incurred, Profit = profit) |>\n  pivot_longer(-year, names_to = \"measure\", values_to = \"amount\") |>\n  ggplot(aes(x = year, y = amount, colour = measure, group = measure)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  scale_y_continuous(labels = money) +\n  labs(\n    title = \"Premium, incurred loss, and profit by year\",\n    x = NULL,\n    y = \"Aggregate amount\"\n  )\n\ntrend_lr <- yearly |>\n  ggplot(aes(x = year, y = loss_ratio, group = 1)) +\n  geom_line(linewidth = 1, colour = \"#d95f0e\") +\n  geom_point(size = 3, colour = \"#d95f0e\") +\n  scale_y_continuous(labels = pct) +\n  labs(\n    title = \"Aggregate loss ratio by year\",\n    x = NULL,\n    y = \"Loss ratio\"\n  )\n\ntrend_amount + trend_lr + plot_layout(widths = c(1.4, 1))\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/unnamed-chunk-8-1.png){width=1056}\n:::\n:::\n\n\n-   Premium and incurred losses both increase over time.\n-   Incurred losses grow faster in 2024.\n-   The 2024 loss-ratio rise indicates weaker profitability despite positive aggregate profit.\n\n### Policy type: comprehensive covers carry higher risk\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_tbl <- portfolio_summary(motor, policy_type) |>\n  arrange(desc(loss_ratio))\n\nkable(policy_tbl, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|policy_type | records|   exposure|  premium|   incurred| claims|     profit| high_loss_rate| p95_loss_ratio| loss_ratio| claim_frequency| avg_premium| avg_severity|\n|:-----------|-------:|----------:|--------:|----------:|------:|----------:|--------------:|--------------:|----------:|---------------:|-----------:|------------:|\n|COMP_N      |   16181|  12342.351| 10344550|  9709280.8|  12907|   635269.3|          0.208|          4.546|      0.939|           1.046|     838.135|      752.249|\n|COMP_E      |   91199|  65040.337| 35712392| 26367075.6|  26687|  9345316.3|          0.116|          3.335|      0.738|           0.410|     549.081|      988.012|\n|TPG         |   36367|  24905.351|  8201409|  5671461.2|   5156|  2529947.8|          0.070|          2.235|      0.692|           0.207|     329.303|     1099.973|\n|CC          |  204636| 144235.186| 49801769| 31563558.5|  31842| 18238210.8|          0.074|          2.497|      0.634|           0.221|     345.282|      991.256|\n|TP          |    5757|   3802.674|  1019549|   553434.5|    507|   466114.6|          0.047|          0.177|      0.543|           0.133|     268.114|     1091.587|\n\n\n:::\n:::\n\n\n-   The policy-type table ranks products by aggregate loss ratio.\n-   It separates product profitability from individual policy-year spread.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_lr <- policy_tbl |>\n  mutate(policy_type = fct_reorder(policy_type, loss_ratio)) |>\n  ggplot(aes(x = policy_type, y = loss_ratio, fill = policy_type)) +\n  geom_col(show.legend = FALSE) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", colour = \"red\") +\n  coord_flip() +\n  scale_y_continuous(labels = pct) +\n  labs(\n    title = \"Aggregate loss ratio by policy type\",\n    subtitle = \"Dashed line marks break-even before expenses.\",\n    x = NULL,\n    y = \"Loss ratio\"\n  )\n\npolicy_box <- motor |>\n  filter(!is.na(policy_type), !is.na(loss_ratio_cap)) |>\n  ggplot(aes(x = fct_reorder(policy_type, loss_ratio_cap, .fun = median), y = loss_ratio_cap)) +\n  geom_boxplot(fill = \"#9ecae1\", outlier.alpha = 0.06) +\n  coord_flip() +\n  scale_y_continuous(labels = pct) +\n  labs(\n    title = \"Spread of capped individual loss ratio\",\n    subtitle = \"Capping exposes group spread without letting extreme outliers dominate.\",\n    x = NULL,\n    y = \"Capped individual loss ratio\"\n  )\n\npolicy_lr + policy_box\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/unnamed-chunk-10-1.png){width=1056}\n:::\n:::\n\n\n-   `COMP_N` has the weakest aggregate profitability, followed by `COMP_E`.\n-   Most policy-year records still have zero or low individual loss ratios.\n-   Weak segment performance is driven by claim frequency and upper-tail losses, not by every policy performing poorly.\n\n### Segment scan: bonus score, fuel type, and circulation area\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseg_long <- bind_rows(\n  portfolio_summary(motor, bonus_score) |>\n    mutate(segment = \"Bonus score\", category = as.character(bonus_score)),\n  portfolio_summary(motor, fuel_type) |>\n    mutate(segment = \"Fuel type\", category = fct_na_value_to_level(as.factor(fuel_type), \"Missing\") |> as.character()),\n  portfolio_summary(motor, circulation_area) |>\n    mutate(segment = \"Circulation area\", category = as.character(circulation_area)),\n  portfolio_summary(motor, payment_frequency) |>\n    mutate(segment = \"Payment frequency\", category = as.character(payment_frequency))\n)\n\nseg_long |>\n  mutate(category = fct_reorder(category, loss_ratio)) |>\n  ggplot(aes(x = category, y = loss_ratio, fill = segment)) +\n  geom_col(show.legend = FALSE) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", colour = \"red\") +\n  coord_flip() +\n  scale_y_continuous(labels = pct) +\n  facet_wrap(~ segment, scales = \"free_y\") +\n  labs(\n    title = \"Loss ratio differs across risk-related categories\",\n    x = NULL,\n    y = \"Aggregate loss ratio\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/unnamed-chunk-11-1.png){width=1056}\n:::\n:::\n\n\n-   Non-good bonus scores, diesel vehicles, urban circulation, and non-annual payment frequencies show higher loss ratios.\n-   These segments are useful screening candidates for underwriting review.\n-   The visual signals are not causal by themselves because exposure, product mix, and vehicle profiles can differ.\n\n### Driver and vehicle age bands\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_driver <- portfolio_summary(motor, driver_age_band) |>\n  mutate(segment = \"Driver age\", category = as.character(driver_age_band))\nage_vehicle <- portfolio_summary(motor, vehicle_age_band) |>\n  mutate(segment = \"Vehicle age\", category = as.character(vehicle_age_band))\n\nbind_rows(age_driver, age_vehicle) |>\n  filter(!is.na(category)) |>\n  ggplot(aes(x = category, y = loss_ratio, group = segment, colour = segment)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  scale_y_continuous(labels = pct) +\n  facet_wrap(~ segment, scales = \"free_x\") +\n  labs(\n    title = \"Loss ratio by driver-age and vehicle-age bands\",\n    x = NULL,\n    y = \"Aggregate loss ratio\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/unnamed-chunk-12-1.png){width=1056}\n:::\n:::\n\n\n-   Driver-age and vehicle-age bands show visible differences in loss ratio.\n-   The patterns are not perfectly monotonic.\n-   Age bands are useful segmentation variables, but not standalone explanations of risk.\n\n### Policy type by year heatmap\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor |>\n  group_by(year, policy_type) |>\n  summarise(\n    exposure = sum(total_exposure, na.rm = TRUE),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    loss_ratio = incurred / premium,\n    .groups = \"drop\"\n  ) |>\n  ggplot(aes(x = year, y = policy_type, fill = loss_ratio)) +\n  geom_tile(colour = \"white\") +\n  geom_text(aes(label = pct(loss_ratio)), colour = \"white\", fontface = \"bold\") +\n  scale_fill_gradient(low = \"#2c7fb8\", high = \"#d7301f\", labels = pct) +\n  labs(\n    title = \"Loss-ratio heatmap by year and policy type\",\n    subtitle = \"Darker red cells identify combinations needing closer monitoring.\",\n    x = NULL,\n    y = NULL,\n    fill = \"Loss ratio\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/unnamed-chunk-13-1.png){width=864}\n:::\n:::\n\n\n-   The heatmap links year-level deterioration with policy-type differences.\n-   Darker cells flag policy-year combinations needing closer monitoring.\n-   The view helps separate persistent segment weakness from one-year deterioration.\n\n### Brand-level volatility screen\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrand_tbl <- motor |>\n  group_by(vehicle_brand) |>\n  summarise(\n    records = n(),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    high_loss_rate = mean(loss_ratio > 1, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  filter(exposure >= 1000)\n\nbrand_tbl |>\n  ggplot(aes(x = claim_frequency, y = loss_ratio, size = exposure)) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", colour = \"red\") +\n  geom_point(alpha = 0.65, colour = \"#08519c\") +\n  geom_text_repel(\n    data = brand_tbl |> slice_max(loss_ratio, n = 8),\n    aes(label = vehicle_brand),\n    size = 3,\n    max.overlaps = 20\n  ) +\n  scale_x_continuous(labels = number_format(accuracy = 0.01)) +\n  scale_y_continuous(labels = pct) +\n  scale_size_continuous(labels = comma, range = c(2, 12)) +\n  labs(\n    title = \"Brand-level screen for high loss ratio and claim frequency\",\n    subtitle = \"Only brands with exposure >= 1,000 are shown.\",\n    x = \"Claim frequency\",\n    y = \"Aggregate loss ratio\",\n    size = \"Exposure\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_backup_before_section3_selection_files/figure-html/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n-   The bubble chart screens brands by claim frequency, loss ratio, and exposure.\n-   Upper-right brands combine higher claim frequency and higher loss ratio.\n-   Large upper-right bubbles should be prioritised for deeper investigation.\n\n### Statistical validation\n\nThe dataset is large and skewed, so visual signals are validated with non-parametric and categorical tests:\n\n-   **Kruskal-Wallis tests** check whether capped individual loss ratio differs across segment groups.\n-   **Chi-square tests** check whether claim occurrence differs across segment groups.\n-   **Spearman correlations** check monotonic relationships between numerical variables and capped loss ratio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_vars <- c(\n  \"policy_type\", \"bonus_score\", \"driver_age_band\", \"vehicle_age_band\",\n  \"fuel_type\", \"circulation_area\", \"payment_frequency\", \"year\"\n)\n\nkw_tbl <- map_dfr(test_vars, \\(v) {\n  kt <- kruskal.test(as.formula(paste(\"loss_ratio_cap ~\", v)), data = motor)\n  tibble(\n    test = \"Kruskal-Wallis\",\n    variable = v,\n    statistic = unname(kt$statistic),\n    p_value = kt$p.value\n  )\n})\n\nchi_tbl <- map_dfr(test_vars, \\(v) {\n  ct <- chisq.test(table(motor[[v]], motor$claim_flag))\n  tibble(\n    test = \"Chi-square\",\n    variable = v,\n    statistic = unname(ct$statistic),\n    p_value = ct$p.value\n  )\n})\n\nvalidation_tbl <- bind_rows(kw_tbl, chi_tbl) |>\n  mutate(p_value_label = format.pval(p_value, digits = 3)) |>\n  select(test, variable, statistic, p_value_label)\n\nkable(validation_tbl, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|test           |variable          | statistic|p_value_label |\n|:--------------|:-----------------|---------:|:-------------|\n|Kruskal-Wallis |policy_type       |   7303.95|<2e-16        |\n|Kruskal-Wallis |bonus_score       |    287.43|<2e-16        |\n|Kruskal-Wallis |driver_age_band   |    267.02|<2e-16        |\n|Kruskal-Wallis |vehicle_age_band  |    303.51|<2e-16        |\n|Kruskal-Wallis |fuel_type         |    799.21|<2e-16        |\n|Kruskal-Wallis |circulation_area  |    211.66|<2e-16        |\n|Kruskal-Wallis |payment_frequency |    399.63|<2e-16        |\n|Kruskal-Wallis |year              |    201.00|<2e-16        |\n|Chi-square     |policy_type       |   6638.42|<2e-16        |\n|Chi-square     |bonus_score       |    297.19|<2e-16        |\n|Chi-square     |driver_age_band   |    463.27|<2e-16        |\n|Chi-square     |vehicle_age_band  |    437.03|<2e-16        |\n|Chi-square     |fuel_type         |    817.15|<2e-16        |\n|Chi-square     |circulation_area  |    225.88|<2e-16        |\n|Chi-square     |payment_frequency |    463.95|<2e-16        |\n|Chi-square     |year              |    197.87|<2e-16        |\n\n\n:::\n:::\n\n\n-   Group-difference tests provide statistical support for the visual segment comparisons.\n-   The p-values should be interpreted with exposure and practical effect size because the dataset is large.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorr_tbl <- map_dfr(\n  c(\"driver_age\", \"vehicle_age\", \"age_driving_licence\", \"vehicle_value\",\n    \"seats\", \"power_to_weight_ratio\", \"total_premium\"),\n  \\(v) {\n    ct <- suppressWarnings(cor.test(motor[[v]], motor$loss_ratio_cap,\n                                    method = \"spearman\", exact = FALSE))\n    tibble(variable = v, spearman_rho = unname(ct$estimate), p_value = ct$p.value)\n  }\n) |>\n  mutate(p_value_label = format.pval(p_value, digits = 3)) |>\n  arrange(desc(abs(spearman_rho)))\n\nkable(corr_tbl |> select(variable, spearman_rho, p_value_label), digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|variable              | spearman_rho|p_value_label |\n|:---------------------|------------:|:-------------|\n|total_premium         |        0.206|<2e-16        |\n|vehicle_value         |        0.070|<2e-16        |\n|power_to_weight_ratio |       -0.035|<2e-16        |\n|vehicle_age           |       -0.029|<2e-16        |\n|driver_age            |       -0.025|<2e-16        |\n|seats                 |        0.017|<2e-16        |\n|age_driving_licence   |        0.001|0.705         |\n\n\n:::\n:::\n\n\n-   Most tests are statistically significant because the dataset is large.\n-   Practical interpretation should combine visual difference, exposure, effect direction, and business relevance.\n-   Total premium has the strongest monotonic relationship with capped loss ratio; most demographic and vehicle correlations are small.\n\n## Key findings\n\n1.  **The portfolio is profitable in aggregate but exposed to a claim-driven upper tail.** Most records have no claim, but a minority of claim records strongly affects incurred loss and loss ratio.\n2.  **Profitability weakens in 2024.** The year-level loss ratio increases, showing that incurred losses grew faster than premium.\n3.  **Policy type is the clearest segmentation signal.** `COMP_N` and `COMP_E` have higher loss ratios than third-party-focused products, suggesting that comprehensive cover requires closer pricing and claim review.\n4.  **Bonus score, fuel type, circulation area, and payment frequency show meaningful differences.** These variables help explain portfolio heterogeneity, but each should be interpreted together with exposure and product mix.\n5.  **Volatility is concentrated in tails, not medians.** Boxplots, capped loss-ratio charts, and the brand bubble chart show why underwriting decisions should account for high-loss policy-year behaviour.\n\n## Recommendations\n\n-   Monitor `COMP_N` and `COMP_E` separately from the rest of the portfolio because their loss-ratio and volatility profile differs materially.\n-   Use the 2024 deterioration as an early-warning signal and review whether it is caused by exposure growth, claim frequency, severity, or a changing product mix.\n-   Treat high-loss brand, fuel, and circulation-area segments as screening candidates for deeper underwriting review rather than as immediate pricing rules.\n-   Extend the analysis with external enrichment, such as regional traffic density, weather exposure, or vehicle repair-cost indicators, to better explain the root causes of underperformance.\n\n## References\n\n-   ISSS608 Take-home Exercise 1 brief: <https://isss608-ay2025-26apr.netlify.app/th_ex/th_ex1>\n-   Motor insurance portfolio data: <https://data.mendeley.com/datasets/sw4jmdb2sm/1>\n-   Senior reference examples used for report structure and visual-analytics presentation style:\n    -   Kylie Tan Jing Yi: <https://akalestale.netlify.app/take-home_ex/take-home_ex01/take-home_ex01>\n    -   Toa Zi Ying Janet: <https://janettoaisss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01>\n    -   Lew Ying Zhen Serena: <https://isss608-spacebun.netlify.app/take-home_ex/take-home_ex1/take-home_ex1>\n    -   Seng Jing Yi: <https://jingyi-vaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01>\n    -   Jaya George: <https://isss608-jayageorge.netlify.app/take-home_ex/take-home_ex01/take-home_ex01>\n",
    "supporting": [
      "TH_Ex1_report_backup_before_section3_selection_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}