{
  "hash": "7296b416d9ff148c0bb47e97c21d3ed1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Visual Analytics for Data Discovery\"\nauthor: \"Cao Jinming\"\ndate: \"20 May 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    code-summary: \"Show the code\"\n---\n\n## Overview\n\nThis report applies visual analytics to a real-world motor insurance portfolio from a Spanish non-life insurer. The exercise brief asks for R-based visual analytics that go beyond dashboard reporting and help discover factors linked to portfolio **profitability** and **volatility**.\n\nThe report is organised in the following structure: context first, analytical sandbox, data preparation, univariate exploration, bivariate analysis, statistical validation, and final findings. The analysis uses the [Mendeley motor portfolio data](https://data.mendeley.com/datasets/sw4jmdb2sm/1).\n\nTwo analytical definitions are used throughout the report:\n\n-   **Profitability** is measured by aggregate `profit = total_premium - total_incurred` and by aggregate `loss_ratio = total_incurred / total_premium`. Lower loss ratio indicates better underwriting profitability before expenses.\n-   **Volatility** is measured by claim occurrence, claim frequency, capped individual loss ratio, high-loss policy rate, and upper-tail loss-ratio behaviour.\n\nThe main question is: *which portfolio segments show weaker profitability or higher volatility, and are those patterns visually and statistically defensible?*\n\n## Analytical sandbox\n\n### R packages and helper functions\n\nThe analytical sandbox uses `tidyverse` for data wrangling, `ggplot2` and extensions for visual analytics, and `knitr` for tabular reporting. Reusable import and portfolio-summary functions are stored in `TH_Ex/th_ex1_common.R` so that the report and slides can use the same definitions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(ggrepel)\nlibrary(plotly)\n\nif (file.exists(\"TH_Ex/th_ex1_common.R\")) {\n  source(\"TH_Ex/th_ex1_common.R\")\n} else {\n  source(\"th_ex1_common.R\")\n}\n\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\nThe table below documents the packages and helper functions used in this report, including the self-created functions stored in `TH_Ex/th_ex1_common.R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsandbox_tools <- tribble(\n  ~type, ~name, ~purpose,\n  \"R package\", \"tidyverse\", \"Main workflow package for data wrangling, reshaping, factor handling, and `ggplot2` visualisation.\",\n  \"R package\", \"readxl\", \"Reads the Excel data dictionary supplied with the motor insurance dataset.\",\n  \"R package\", \"scales\", \"Formats axis labels and table values as Euro amounts, percentages, and comma-separated counts.\",\n  \"R package\", \"patchwork\", \"Combines multiple `ggplot2` charts into one visual layout for side-by-side comparison.\",\n  \"R package\", \"knitr\", \"Creates clean report tables from R data frames using `kable()`.\",\n  \"R package\", \"ggrepel\", \"Provides non-overlapping text-labelling functions for scatterplots when segment labels need to remain readable.\",\n  \"R package\", \"plotly\", \"Converts selected `ggplot2` point and scatter plots into interactive HTML charts with hover tooltips using `ggplotly()`.\",\n  \"Self-created helper\", \"find_project_root()\", \"Locates the Quarto project root by searching upward for `_quarto.yml`, making file paths more robust.\",\n  \"Self-created helper\", \"project_path()\", \"Builds project-relative file paths from the detected project root.\",\n  \"Self-created helper\", \"ensure_th1_data()\", \"Checks whether the raw CSV and data dictionary exist locally; if not, downloads and extracts them from Mendeley Data.\",\n  \"Self-created helper\", \"load_th1_motor()\", \"Imports the semicolon-delimited motor portfolio CSV and creates derived analytical variables such as profit, loss ratio, claim flag, severity, and age bands.\",\n  \"Self-created helper\", \"portfolio_summary()\", \"Aggregates portfolio records by a selected segment and calculates exposure, premium, incurred loss, claims, profit, loss ratio, claim frequency, severity, and high-loss indicators.\",\n  \"Self-created helper\", \"money\", \"Reusable Euro currency labeller created with `scales::label_dollar()`.\",\n  \"Self-created helper\", \"pct\", \"Reusable percentage labeller created with `scales::label_percent()`.\",\n  \"Base R / utils\", \"download.file()\", \"Downloads the Mendeley data zip file when the raw data is not already available locally.\",\n  \"Base R / utils\", \"utils::unzip()\", \"Extracts the downloaded zip file so the CSV and Excel dictionary can be copied into the project data folder.\"\n)\n\nkable(sandbox_tools)\n```\n\n::: {.cell-output-display}\n\n\n|type                |name                |purpose                                                                                                                                                                              |\n|:-------------------|:-------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|R package           |tidyverse           |Main workflow package for data wrangling, reshaping, factor handling, and `ggplot2` visualisation.                                                                                   |\n|R package           |readxl              |Reads the Excel data dictionary supplied with the motor insurance dataset.                                                                                                           |\n|R package           |scales              |Formats axis labels and table values as Euro amounts, percentages, and comma-separated counts.                                                                                       |\n|R package           |patchwork           |Combines multiple `ggplot2` charts into one visual layout for side-by-side comparison.                                                                                               |\n|R package           |knitr               |Creates clean report tables from R data frames using `kable()`.                                                                                                                      |\n|R package           |ggrepel             |Provides non-overlapping text-labelling functions for scatterplots when segment labels need to remain readable.                                                                      |\n|R package           |plotly              |Converts selected `ggplot2` point and scatter plots into interactive HTML charts with hover tooltips using `ggplotly()`.                                                             |\n|Self-created helper |find_project_root() |Locates the Quarto project root by searching upward for `_quarto.yml`, making file paths more robust.                                                                                |\n|Self-created helper |project_path()      |Builds project-relative file paths from the detected project root.                                                                                                                   |\n|Self-created helper |ensure_th1_data()   |Checks whether the raw CSV and data dictionary exist locally; if not, downloads and extracts them from Mendeley Data.                                                                |\n|Self-created helper |load_th1_motor()    |Imports the semicolon-delimited motor portfolio CSV and creates derived analytical variables such as profit, loss ratio, claim flag, severity, and age bands.                        |\n|Self-created helper |portfolio_summary() |Aggregates portfolio records by a selected segment and calculates exposure, premium, incurred loss, claims, profit, loss ratio, claim frequency, severity, and high-loss indicators. |\n|Self-created helper |money               |Reusable Euro currency labeller created with `scales::label_dollar()`.                                                                                                               |\n|Self-created helper |pct                 |Reusable percentage labeller created with `scales::label_percent()`.                                                                                                                 |\n|Base R / utils      |download.file()     |Downloads the Mendeley data zip file when the raw data is not already available locally.                                                                                             |\n|Base R / utils      |utils::unzip()      |Extracts the downloaded zip file so the CSV and Excel dictionary can be copied into the project data folder.                                                                         |\n\n\n:::\n:::\n\n\n### Data source and import\n\nThe dataset is the open-access motor insurance portfolio from Mendeley Data. The helper function downloads and extracts the data if the CSV and data dictionary are not already available locally. The CSV is semicolon-delimited.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor <- load_th1_motor()\ndict <- read_excel(th1_dict_path)\n\nglimpse(motor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 55\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <fct> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ claim_flag                  <lgl> FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FA…\n$ profit                      <dbl> 279.5576, 546.6234, 315.7396, -2001.7291, …\n$ loss_ratio                  <dbl> 0.0000000, 0.0000000, 0.4246231, 4.4239104…\n$ loss_ratio_cap              <dbl> 0.0000000, 0.0000000, 0.4246231, 4.4239104…\n$ claim_frequency             <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ severity                    <dbl> NA, NA, 233.0130, 1293.1807, NA, NA, NA, N…\n$ driver_age_band             <fct> 46-55, 36-45, 36-45, 36-45, 36-45, 46-55, …\n$ vehicle_age_band            <fct> 21+, 21+, 21+, 21+, 21+, 21+, 21+, 8-12, 1…\n```\n\n\n:::\n:::\n\n\n### Portfolio size and derived variables\n\nThe imported portfolio contains policy-year records from 2022 to 2024. The table below documents the derived variables and summary functions used to construct the portfolio-size table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nderived_variable_reference <- tribble(\n  ~type, ~name, ~purpose,\n  \"Derived variable\", \"profit\", \"Measures underwriting result at policy-year level: total premium minus total incurred loss.\",\n  \"Derived variable\", \"loss_ratio\", \"Measures loss burden relative to premium: total incurred loss divided by total premium.\",\n  \"Derived variable\", \"loss_ratio_cap\", \"Caps individual loss ratio at the 99th percentile so plots are not dominated by extreme outliers.\",\n  \"Derived variable\", \"claim_flag\", \"Marks whether a policy-year has at least one claim; used for claim-record share and volatility checks.\",\n  \"Derived variable\", \"claim_frequency\", \"Standardises claim count by exposure: total claims divided by total exposure.\",\n  \"Derived variable\", \"severity\", \"Measures average incurred loss per claim; defined only for records with at least one claim.\",\n  \"Derived variable\", \"driver_age_band\", \"Groups driver age into bands for segment-level profitability and volatility comparison.\",\n  \"Derived variable\", \"vehicle_age_band\", \"Groups vehicle age into bands for segment-level profitability and volatility comparison.\",\n  \"Summary table\", \"portfolio_size\", \"Stores the headline portfolio-size, premium, incurred loss, profit, loss-ratio, and claim-share metrics displayed in this section.\"\n)\n\nkable(derived_variable_reference)\n```\n\n::: {.cell-output-display}\n\n\n|type             |name             |purpose                                                                                                                            |\n|:----------------|:----------------|:----------------------------------------------------------------------------------------------------------------------------------|\n|Derived variable |profit           |Measures underwriting result at policy-year level: total premium minus total incurred loss.                                        |\n|Derived variable |loss_ratio       |Measures loss burden relative to premium: total incurred loss divided by total premium.                                            |\n|Derived variable |loss_ratio_cap   |Caps individual loss ratio at the 99th percentile so plots are not dominated by extreme outliers.                                  |\n|Derived variable |claim_flag       |Marks whether a policy-year has at least one claim; used for claim-record share and volatility checks.                             |\n|Derived variable |claim_frequency  |Standardises claim count by exposure: total claims divided by total exposure.                                                      |\n|Derived variable |severity         |Measures average incurred loss per claim; defined only for records with at least one claim.                                        |\n|Derived variable |driver_age_band  |Groups driver age into bands for segment-level profitability and volatility comparison.                                            |\n|Derived variable |vehicle_age_band |Groups vehicle age into bands for segment-level profitability and volatility comparison.                                           |\n|Summary table    |portfolio_size   |Stores the headline portfolio-size, premium, incurred loss, profit, loss-ratio, and claim-share metrics displayed in this section. |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio_size <- tibble(\n  measure = c(\n    \"Policy-year records\",\n    \"Distinct insured IDs\",\n    \"Calendar years\",\n    \"Variables after derivation\",\n    \"Aggregate premium\",\n    \"Aggregate incurred loss\",\n    \"Aggregate profit\",\n    \"Aggregate loss ratio\",\n    \"Claim-record share\"\n  ),\n  value = c(\n    comma(nrow(motor)),\n    comma(n_distinct(motor$insured_id)),\n    paste(levels(motor$year), collapse = \", \"),\n    comma(ncol(motor)),\n    money(sum(motor$total_premium, na.rm = TRUE)),\n    money(sum(motor$total_incurred, na.rm = TRUE)),\n    money(sum(motor$profit, na.rm = TRUE)),\n    pct(sum(motor$total_incurred, na.rm = TRUE) / sum(motor$total_premium, na.rm = TRUE)),\n    pct(mean(motor$claim_flag, na.rm = TRUE))\n  )\n)\n\nkable(portfolio_size)\n```\n\n::: {.cell-output-display}\n\n\n|measure                    |value            |\n|:--------------------------|:----------------|\n|Policy-year records        |354,140          |\n|Distinct insured IDs       |185,678          |\n|Calendar years             |2022, 2023, 2024 |\n|Variables after derivation |55               |\n|Aggregate premium          |€105,079,669     |\n|Aggregate incurred loss    |€73,864,811      |\n|Aggregate profit           |€31,214,859      |\n|Aggregate loss ratio       |70.3%            |\n|Claim-record share         |14.3%            |\n\n\n:::\n:::\n\n\n-   Portfolio is profitable in aggregate before expenses.\n-   Aggregate totals can hide segment-level volatility.\n-   The remaining analysis focuses on distributions, outliers, and segment comparisons.\n\n### Data quality checks\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_tbl <- motor |>\n  summarise(across(everything(), ~sum(is.na(.x)))) |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"missing_records\") |>\n  filter(missing_records > 0) |>\n  mutate(missing_share = missing_records / nrow(motor)) |>\n  arrange(desc(missing_records))\n\nkable(missing_tbl, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|variable            | missing_records| missing_share|\n|:-------------------|---------------:|-------------:|\n|severity            |          303333|        0.8565|\n|fuel_type           |            1287|        0.0036|\n|vehicle_value       |             513|        0.0014|\n|loss_ratio          |              49|        0.0001|\n|loss_ratio_cap      |              49|        0.0001|\n|claim_frequency     |              49|        0.0001|\n|vehicle_age         |               2|        0.0000|\n|age_driving_licence |               2|        0.0000|\n|vehicle_age_band    |               2|        0.0000|\n\n\n:::\n:::\n\n\n-   Core premium and incurred-loss variables are mostly complete.\n-   `severity` has many missing values because it is defined only for claim records.\n-   Missing `fuel_type`, `vehicle_value`, `vehicle_age`, and `age_driving_licence` records are retained to avoid distorting exposure totals.\n\n## Task 1: Univariate visual analytics\n\nThis section now focuses on variables that are most useful for investigating trends in underlying loss drivers and for supporting segmentation and underwriting strategy. Administrative fields and very detailed sub-components are not shown here unless they add clear business value to the loss-driver story.\n\nThe selected variables are chosen using two criteria:\n\n- **Data distribution:** variables with meaningful spread, strong zero inflation, skewness, or visible segment imbalance are useful for visual discovery.\n- **Business relevance:** variables should help explain claim frequency, claim severity, pricing adequacy, exposure mix, or potential enrichment opportunities using external data such as geography, vehicle market data, repair-cost indices, crime risk, weather, or traffic density.\n\n### Best use cases in this dataset\n\nThe table below highlights the monetary variable groups where cross-component distribution-based visual analytics are especially useful. These variables have strong skewness, zero inflation, or sparse positive values, so they benefit from ridgeline comparisons after the individual univariate profiles.\n\n| Variable group | Variables | Recommended R visual |\n|---|---|---|\n| Premium components | `liability_premium`, `property_damage_premium`, `theft_premium`, `fire_premium`, `glass_premium`, `legal_protection_premium`, `occupants_premium` | Ridgeline density plot or half-eye plot |\n| Optional premiums | `theft_premium`, `fire_premium`, `glass_premium`, `legal_protection_premium`, `occupants_premium` | Ridgeline plot on positive values only |\n| Incurred claim costs | `liability_incurred`, `property_incurred`, `theft_incurred`, `fire_incurred`, `glass_incurred`, `legal_protection_incurred`, `occupants_incurred` | Ridgeline plot with log scale, positive values only |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nridge_empty_plot <- function(title, message) {\n  ggplot() +\n    annotate(\"text\", x = 0, y = 0, label = message) +\n    theme_void() +\n    labs(title = title)\n}\n\nmanual_ridgeline <- function(df, vars, title,\n                             positive_only = FALSE, log10_x = FALSE,\n                             cap_quantile = NULL, x_labels = comma,\n                             x_axis_title = NULL) {\n  plot_df <- df |>\n    select(all_of(vars)) |>\n    pivot_longer(everything(), names_to = \"variable\", values_to = \"value\") |>\n    mutate(value = suppressWarnings(as.numeric(value))) |>\n    filter(is.finite(value))\n\n  if (positive_only) {\n    plot_df <- plot_df |> filter(value > 0)\n  }\n\n  if (nrow(plot_df) == 0) {\n    return(ridge_empty_plot(title, \"No finite values available for this variable group.\"))\n  }\n\n  if (log10_x) {\n    plot_df <- plot_df |>\n      mutate(value_plot = log10(value + 1))\n  } else if (!is.null(cap_quantile)) {\n    cap_value <- quantile(plot_df$value, cap_quantile, na.rm = TRUE)\n    plot_df <- plot_df |>\n      mutate(value_plot = pmin(value, cap_value))\n  } else {\n    plot_df <- plot_df |>\n      mutate(value_plot = value)\n  }\n\n  variable_levels <- rev(vars)\n\n  density_df <- plot_df |>\n    mutate(variable = factor(variable, levels = variable_levels)) |>\n    group_by(variable) |>\n    group_modify(~{\n      if (nrow(.x) < 2 || n_distinct(.x$value_plot) < 2) {\n        return(tibble(x = numeric(), density = numeric()))\n      }\n      density_obj <- density(.x$value_plot, n = 256, na.rm = TRUE, from = 0)\n      tibble(x = pmax(density_obj$x, 0), density = density_obj$y)\n    }) |>\n    ungroup() |>\n    group_by(variable) |>\n    mutate(\n      y_base = as.numeric(variable),\n      y_ridge = y_base + density / max(density, na.rm = TRUE) * 0.82\n    ) |>\n    ungroup()\n\n  if (nrow(density_df) == 0) {\n    return(ridge_empty_plot(title, \"Not enough variation to estimate density ridges.\"))\n  }\n\n  p <- ggplot(density_df, aes(x = x, group = variable, fill = variable)) +\n    geom_ribbon(aes(ymin = y_base, ymax = y_ridge), alpha = 0.68, colour = NA) +\n    geom_line(aes(y = y_ridge, colour = variable), linewidth = 0.45, show.legend = FALSE) +\n    scale_y_continuous(\n      breaks = seq_along(variable_levels),\n      labels = variable_levels,\n      expand = expansion(mult = c(0.03, 0.10))\n    ) +\n    guides(fill = \"none\") +\n    labs(\n      title = title,\n      x = x_axis_title,\n      y = NULL\n    ) +\n    theme(\n      panel.grid.major.y = element_blank(),\n      panel.grid.minor = element_blank()\n    )\n\n  if (log10_x) {\n    p + scale_x_continuous(\n      limits = c(0, NA),\n      expand = expansion(mult = c(0, 0.03)),\n      labels = function(x) x_labels(10^x - 1)\n    )\n  } else {\n    p + scale_x_continuous(\n      limits = c(0, NA),\n      expand = expansion(mult = c(0, 0.03)),\n      labels = x_labels\n    )\n  }\n}\n\npremium_component_vars <- c(\n  \"liability_premium\", \"property_damage_premium\", \"theft_premium\",\n  \"fire_premium\", \"glass_premium\", \"legal_protection_premium\",\n  \"occupants_premium\"\n)\noptional_premium_vars <- c(\n  \"theft_premium\", \"fire_premium\", \"glass_premium\",\n  \"legal_protection_premium\", \"occupants_premium\"\n)\nincurred_component_vars <- c(\n  \"liability_incurred\", \"property_incurred\", \"theft_incurred\",\n  \"fire_incurred\", \"glass_incurred\", \"legal_protection_incurred\",\n  \"occupants_incurred\"\n)\ndensity_estimation_vars <- unique(c(\n  premium_component_vars,\n  optional_premium_vars,\n  incurred_component_vars\n))\n```\n:::\n\n\n```{=html}\n<style>\n.observation-box {\n  background-color: #fff3cd;\n  border-left: 6px solid #d95f0e;\n  border-radius: 6px;\n  padding: 0.85rem 1rem;\n  margin: 1rem 0 1.25rem 0;\n}\n.observation-box strong {\n  color: #7a3e00;\n}\n</style>\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_profile <- motor |>\n  mutate(\n    year_numeric = as.numeric(as.character(year)),\n    licence_years_held = if_else(\n      !is.na(year_numeric) & !is.na(age_driving_licence),\n      year_numeric - age_driving_licence,\n      NA_real_\n    )\n  )\n\nloss_driver_spec <- tribble(\n  ~variable, ~variable_type, ~loss_driver_relevance, ~visual_family, ~top_n,\n  \"year\", \"Time / ordinal categorical\", \"Portfolio volume and loss experience must be compared against calendar-year mix.\", \"year\", NA_real_,\n  \"policy_type\", \"Categorical\", \"Coverage structure affects claim exposure and pricing adequacy: TP, TPG, CC, COMP_E, and COMP_N represent increasing breadth of cover.\", \"categorical\", NA_real_,\n  \"business_type\", \"Categorical\", \"New business (NB) versus portfolio business (P) can show different selection and renewal-risk patterns.\", \"categorical\", NA_real_,\n  \"bonus_score\", \"Ordinal categorical\", \"Claim-history quality is a practical underwriting signal: G is favourable, N is neutral, and B is poor claims history.\", \"ordinal\", NA_real_,\n  \"driver_age\", \"Numerical\", \"Driver age is a core behavioural risk proxy with meaningful distribution spread.\", \"numeric\", NA_real_,\n  \"licence_years_held\", \"Derived numerical\", \"Raw `age_driving_licence` records the calendar year of licence issue, so years-held is derived for more direct driving-experience interpretation.\", \"numeric\", NA_real_,\n  \"vehicle_age\", \"Numerical\", \"Vehicle age can affect repair economics, safety technology, and claim handling outcomes.\", \"numeric\", NA_real_,\n  \"vehicle_value\", \"Numerical money/value\", \"Vehicle value is directly linked to potential claim severity and sum insured.\", \"money\", NA_real_,\n  \"power_to_weight_ratio\", \"Numerical\", \"Approximate kg-per-horsepower ratio is a vehicle performance proxy; its direction must be read carefully because higher values imply less power per unit weight.\", \"numeric\", NA_real_,\n  \"vehicle_brand\", \"High-cardinality categorical\", \"Brand can capture differences in repair cost, parts availability, theft attractiveness, and vehicle profile.\", \"categorical\", 15,\n  \"municipality_type\", \"Categorical\", \"Municipality type distinguishes inland (I), coastal (C), and island (IS) contexts that can indicate environmental, road, and claims-service differences.\", \"categorical\", NA_real_,\n  \"circulation_area\", \"Categorical\", \"Urban (U) or rural (R) circulation affects traffic density and accident exposure.\", \"categorical\", NA_real_,\n  \"total_premium\", \"Numerical money\", \"Premium distribution shows price level, product mix, and possible pricing outliers.\", \"premium\", NA_real_,\n  \"theft_premium\", \"Optional premium\", \"Theft cover uptake indicates where theft exposure is explicitly insured.\", \"optional_premium\", NA_real_,\n  \"glass_premium\", \"Optional premium\", \"Glass cover uptake may influence small-claim frequency and optional-coverage behaviour.\", \"optional_premium\", NA_real_,\n  \"total_claims\", \"Count\", \"Claim count is the direct frequency outcome for the portfolio.\", \"claim_count\", NA_real_,\n  \"liability_claims\", \"Count\", \"Liability claim count is a key third-party frequency driver.\", \"claim_count\", NA_real_,\n  \"total_incurred\", \"Numerical money\", \"Total incurred cost captures overall severity and tail-loss behaviour.\", \"incurred\", NA_real_,\n  \"liability_injury_incurred\", \"Numerical money\", \"Bodily injury incurred cost is often severe, skewed, and sensitive to legal or medical inflation.\", \"incurred\", NA_real_,\n  \"property_incurred\", \"Numerical money\", \"Property incurred cost reflects vehicle repair and damage severity.\", \"incurred\", NA_real_,\n  \"total_exposure\", \"Numerical\", \"Exposure records effective time-on-risk in policy years; it usually ranges from 0 to 1 but can exceed 1 for longer contracts.\", \"exposure\", NA_real_\n)\nmissing_from_data <- setdiff(loss_driver_spec$variable, names(motor_profile))\nif (length(missing_from_data) > 0) {\n  stop(paste(\"Variables missing from motor_profile:\", paste(missing_from_data, collapse = \", \")))\n}\n\nformat_profile_value <- function(x, var = NULL) {\n  if (length(x) == 0 || is.na(x) || !is.finite(x)) return(\"NA\")\n  if (!is.null(var) && str_detect(var, \"premium|incurred|vehicle_value|profit|severity\")) {\n    return(money(x))\n  }\n  comma(round(x, 2))\n}\n\nnumeric_profile_summary <- function(df, var) {\n  x <- suppressWarnings(as.numeric(df[[var]]))\n  finite_x <- x[is.finite(x)]\n  tibble(\n    metric = c(\"Missing records\", \"Missing share\", \"Zero share\", \"Minimum\", \"Median\", \"Mean\", \"95th percentile\", \"Maximum\"),\n    value = c(\n      comma(sum(is.na(x))),\n      pct(mean(is.na(x))),\n      if (length(finite_x) == 0) \"NA\" else pct(mean(finite_x == 0)),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(min(finite_x), var),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(median(finite_x), var),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(mean(finite_x), var),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(quantile(finite_x, 0.95, na.rm = TRUE), var),\n      if (length(finite_x) == 0) \"NA\" else format_profile_value(max(finite_x), var)\n    )\n  )\n}\n\ncategorical_profile_summary <- function(df, var) {\n  x <- df[[var]]\n  non_missing <- x[!is.na(x)]\n  tab <- sort(table(non_missing), decreasing = TRUE)\n  tibble(\n    metric = c(\"Missing records\", \"Missing share\", \"Distinct non-missing values\", \"Top category\", \"Top-category share\"),\n    value = c(\n      comma(sum(is.na(x))),\n      pct(mean(is.na(x))),\n      comma(n_distinct(x, na.rm = TRUE)),\n      if (length(tab) == 0) \"NA\" else names(tab)[1],\n      if (length(tab) == 0) \"NA\" else pct(as.numeric(tab[1]) / length(non_missing))\n    )\n  )\n}\n\nprofile_summary <- function(df, var, family) {\n  if (family %in% c(\"categorical\", \"ordinal\", \"year\", \"discrete\")) return(categorical_profile_summary(df, var))\n  numeric_profile_summary(df, var)\n}\n\nempty_plot <- function(title, message) {\n  ggplot() +\n    annotate(\"text\", x = 0, y = 0, label = message) +\n    theme_void() +\n    labs(title = title)\n}\n\nhist_box_visual <- function(df, var, title = NULL, subtitle = NULL, positive_only = FALSE, log_scale = FALSE) {\n  plot_df <- tibble(value = suppressWarnings(as.numeric(df[[var]]))) |>\n    filter(is.finite(value))\n  if (positive_only) plot_df <- plot_df |> filter(value > 0)\n\n  if (nrow(plot_df) == 0) {\n    return(empty_plot(paste(\"Distribution of\", var), \"No finite values available\"))\n  }\n\n  if (!log_scale) {\n    lower <- quantile(plot_df$value, 0.01, na.rm = TRUE)\n    upper <- quantile(plot_df$value, 0.99, na.rm = TRUE)\n    plot_df <- plot_df |>\n      mutate(value_plot = pmin(pmax(value, lower), upper))\n    plot_subtitle <- coalesce(subtitle, \"Histogram and boxplot; values are capped at the 1st and 99th percentiles for readability only.\")\n  } else {\n    plot_df <- plot_df |> mutate(value_plot = value)\n    plot_subtitle <- coalesce(subtitle, \"Positive values only; x-axis is log-scaled to reveal skewed claim-cost severity.\")\n  }\n\n  x_labeller <- if (str_detect(var, \"premium|incurred|vehicle_value|profit|severity\")) money else comma\n\n  hist <- ggplot(plot_df, aes(x = value_plot)) +\n    geom_histogram(bins = 35, colour = \"white\", fill = \"#2c7fb8\") +\n    labs(x = var, y = \"Number of records\")\n\n  box <- ggplot(plot_df, aes(x = value_plot, y = \"\")) +\n    geom_boxplot(fill = \"#a6bddb\", colour = \"#045a8d\", outlier.alpha = 0.35) +\n    labs(x = var, y = NULL)\n\n  if (log_scale) {\n    hist <- hist + scale_x_log10(labels = x_labeller)\n    box <- box + scale_x_log10(labels = x_labeller)\n  } else {\n    hist <- hist + scale_x_continuous(labels = x_labeller)\n    box <- box + scale_x_continuous(labels = x_labeller)\n  }\n\n  hist / box +\n    plot_layout(heights = c(3, 1)) +\n    plot_annotation(\n      title = coalesce(title, paste(\"Distribution of\", var)),\n      subtitle = plot_subtitle\n    )\n}\n\nzero_positive_bar <- function(df, var, positive_label = \"Positive\") {\n  fill_values <- c(\"#bdbdbd\", \"#2c7fb8\", \"#fdae6b\", \"#756bb1\")\n  names(fill_values) <- c(\"Zero\", positive_label, \"Negative\", \"Missing\")\n\n  tibble(value = suppressWarnings(as.numeric(df[[var]]))) |>\n    mutate(status = case_when(\n      is.na(value) ~ \"Missing\",\n      value > 0 ~ positive_label,\n      value == 0 ~ \"Zero\",\n      TRUE ~ \"Negative\"\n    )) |>\n    count(status, name = \"n\") |>\n    mutate(\n      share = n / sum(n),\n      status = factor(status, levels = c(\"Zero\", positive_label, \"Negative\", \"Missing\"))\n    ) |>\n    ggplot(aes(x = status, y = share, fill = status)) +\n    geom_col(show.legend = FALSE) +\n    geom_text(aes(label = percent(share, accuracy = 0.1)), vjust = -0.25, size = 3.5) +\n    scale_y_continuous(labels = percent, limits = c(0, NA)) +\n    scale_fill_manual(values = fill_values) +\n    labs(\n      title = paste(\"Zero versus positive\", var),\n      x = NULL,\n      y = \"Share of records\"\n    )\n}\n\noptional_premium_visual <- function(df, var) {\n  zero_positive_bar(df, var, positive_label = \"Positive premium\") /\n    hist_box_visual(\n      df, var,\n      title = paste(\"Positive premium distribution for\", var),\n      subtitle = \"Positive premium values only; zero premiums are shown separately above.\",\n      positive_only = TRUE,\n      log_scale = FALSE\n    ) +\n    plot_layout(heights = c(1, 2.4))\n}\n\nincurred_visual <- function(df, var) {\n  zero_positive_bar(df, var, positive_label = \"Positive incurred\") /\n    hist_box_visual(\n      df, var,\n      title = paste(\"Positive incurred-cost distribution for\", var),\n      positive_only = TRUE,\n      log_scale = TRUE\n    ) +\n    plot_layout(heights = c(1, 2.4))\n}\n\nclaim_count_visual <- function(df, var) {\n  count_plot <- tibble(value = suppressWarnings(as.numeric(df[[var]]))) |>\n    mutate(claim_count = if_else(is.na(value), \"Missing\", as.character(value))) |>\n    count(claim_count, name = \"n\") |>\n    mutate(claim_count = fct_reorder(claim_count, suppressWarnings(as.numeric(claim_count)), .na_rm = TRUE)) |>\n    ggplot(aes(x = claim_count, y = n)) +\n    geom_col(fill = \"#2c7fb8\") +\n    labs(\n      title = paste(\"Claim-count distribution for\", var),\n      x = \"Claim count\",\n      y = \"Number of records\"\n    )\n\n  flag_plot <- tibble(value = suppressWarnings(as.numeric(df[[var]]))) |>\n    mutate(status = case_when(\n      is.na(value) ~ \"Missing\",\n      value == 0 ~ \"0 claims\",\n      value > 0 ~ \"1 or more claims\",\n      TRUE ~ \"Negative\"\n    )) |>\n    count(status, name = \"n\") |>\n    mutate(\n      share = n / sum(n),\n      status = factor(status, levels = c(\"0 claims\", \"1 or more claims\", \"Negative\", \"Missing\"))\n    ) |>\n    ggplot(aes(x = status, y = share, fill = status)) +\n    geom_col(show.legend = FALSE) +\n    geom_text(aes(label = percent(share, accuracy = 0.1)), vjust = -0.25, size = 3.5) +\n    scale_y_continuous(labels = percent, limits = c(0, NA)) +\n    scale_fill_manual(values = c(\"0 claims\" = \"#bdbdbd\", \"1 or more claims\" = \"#2c7fb8\", \"Negative\" = \"#fdae6b\", \"Missing\" = \"#756bb1\")) +\n    labs(\n      title = paste(\"Claim occurrence for\", var),\n      x = NULL,\n      y = \"Share of records\"\n    )\n\n  count_plot / flag_plot + plot_layout(heights = c(1.4, 1))\n}\n\nyear_visual <- function(df, var) {\n  p <- df |>\n    transmute(year_value = fct_na_value_to_level(as.factor(.data[[var]]), level = \"Missing\")) |>\n    count(year_value, name = \"n\") |>\n    mutate(hover = paste0(\n      \"Year: \", year_value,\n      \"<br>Records: \", comma(n)\n    )) |>\n    ggplot(aes(x = year_value, y = n, group = 1, text = hover)) +\n    geom_col(fill = \"#756bb1\", alpha = 0.75) +\n    geom_line(colour = \"#d95f0e\", linewidth = 1) +\n    geom_point(colour = \"#d95f0e\", size = 2) +\n    labs(\n      title = \"Policy-year record counts by year\",\n      x = \"Year\",\n      y = \"Number of records\"\n    )\n\n  ggplotly(p, tooltip = \"text\")\n}\n\ncategorical_visual <- function(df, var, family = \"categorical\", top_n = NA_real_) {\n  plot_df <- df |>\n    transmute(category = fct_na_value_to_level(as.factor(.data[[var]]), level = \"Missing\")) |>\n    count(category, name = \"n\")\n\n  if (family == \"ordinal\" && var == \"bonus_score\") {\n    level_order <- c(intersect(c(\"B\", \"N\", \"G\"), as.character(plot_df$category)),\n                     setdiff(as.character(plot_df$category), c(\"B\", \"N\", \"G\")))\n    plot_df <- plot_df |> mutate(category = factor(as.character(category), levels = level_order))\n  } else {\n    if (!is.na(top_n)) {\n      plot_df <- plot_df |>\n        mutate(category = fct_lump_n(category, n = top_n, w = n, other_level = \"Other\")) |>\n        group_by(category) |>\n        summarise(n = sum(n), .groups = \"drop\")\n    }\n    plot_df <- plot_df |> mutate(category = fct_reorder(category, n))\n  }\n\n  plot_df |>\n    mutate(share = n / sum(n)) |>\n    ggplot(aes(x = category, y = share)) +\n    geom_col(fill = \"#756bb1\") +\n    coord_flip() +\n    scale_y_continuous(labels = percent) +\n    labs(\n      title = paste(\"Composition of\", var),\n      subtitle = if (!is.na(top_n)) paste(\"Top\", top_n, \"categories retained; remaining categories grouped as Other.\") else \"Bars show share of policy-year records.\",\n      x = NULL,\n      y = \"Share of records\"\n    )\n}\n\nmake_profile_visual <- function(df, spec_row) {\n  var <- spec_row$variable\n  family <- spec_row$visual_family\n  top_n <- spec_row$top_n\n\n  if (family == \"year\") return(year_visual(df, var))\n  if (family %in% c(\"categorical\", \"ordinal\", \"discrete\")) return(categorical_visual(df, var, family, top_n))\n  if (family == \"optional_premium\") return(optional_premium_visual(df, var))\n  if (family == \"incurred\") return(incurred_visual(df, var))\n  if (family == \"claim_count\") return(claim_count_visual(df, var))\n  hist_box_visual(df, var)\n}\n\nprofile_observations <- function(df, spec_row) {\n  var <- spec_row$variable\n  family <- spec_row$visual_family\n  x <- df[[var]]\n\n  if (family %in% c(\"categorical\", \"ordinal\", \"year\", \"discrete\")) {\n    tab <- sort(table(x, useNA = \"no\"), decreasing = TRUE)\n    missing_share <- mean(is.na(x))\n    distinct_values <- n_distinct(x, na.rm = TRUE)\n    top_category <- if (length(tab) == 0) \"NA\" else names(tab)[1]\n    top_share <- if (length(tab) == 0) NA_real_ else as.numeric(tab[1]) / sum(tab)\n\n    bullets <- c()\n    if (length(tab) > 0) {\n      bullets <- c(bullets, paste0(\"The distribution is led by `\", top_category, \"`, representing \", pct(top_share), \" of non-missing records.\"))\n    }\n    if (distinct_values > 20) {\n      bullets <- c(bullets, paste0(\"There are \", distinct_values, \" distinct values, so interpretation should focus on the leading groups and not over-read rare categories.\"))\n    } else if (!is.na(top_share) && top_share > 0.70) {\n      bullets <- c(bullets, \"The concentration in one category means aggregate portfolio results may be strongly shaped by this dominant segment.\")\n    } else if (length(tab) > 1) {\n      bullets <- c(bullets, \"The variable has enough category spread to support segment comparison in the bivariate loss-ratio analysis.\")\n    }\n    if (missing_share > 0) {\n      bullets <- c(bullets, paste0(\"Missing values account for \", pct(missing_share), \", so missingness should be retained as a visible underwriting/data-quality signal.\"))\n    }\n\n    meaning <- case_when(\n      var == \"year\" ~ paste0(\"This year mix matters because any heavier concentration in `\", top_category, \"` can influence observed premium growth, claim emergence, and inflation effects.\"),\n      var == \"policy_type\" ~ paste0(\"Policy type records coverage breadth: TP is basic third-party, TPG adds glass, CC combines third-party with additional covers, COMP_E is comprehensive with excess, and COMP_N is comprehensive without excess; because `\", top_category, \"` is largest, product mix must be controlled before interpreting loss differences.\"),\n      var == \"business_type\" ~ paste0(\"Business type separates new business (NB) from portfolio business (P); the dominant `\", top_category, \"` mix affects whether observed risk is mainly renewal exposure or new-selection risk.\"),\n      var == \"bonus_score\" ~ paste0(\"Bonus score maps claim-history quality where G is favourable, N is neutral, and B is poor; this makes the variable a direct prior-claims signal for later claim-frequency comparison.\"),\n      var == \"vehicle_brand\" ~ \"Brand concentration can hide repair-cost, theft, and parts-availability differences; top brands are good candidates for enrichment with market repair-cost and theft-rate data.\",\n      var == \"fuel_type\" ~ paste0(\"Fuel type is retained as D for diesel and G for gasoline, so any difference should be interpreted together with vehicle age, value, and product mix.\"),\n      var == \"municipality_type\" ~ paste0(\"Municipality type separates inland (I), coastal (C), and island (IS) contexts; the dominant `\", top_category, \"` context should be considered when enriching with weather, road-density, flood, or local economic indicators.\"),\n      var == \"circulation_area\" ~ paste0(\"Circulation area separates urban (U) from rural (R) exposure; the `\", top_category, \"` pattern should be compared with claim frequency and severity, not only record count.\"),\n      TRUE ~ paste0(\"This distribution helps decide whether `\", var, \"` should be used as a segmentation variable or mainly as a control variable.\")\n    )\n    bullets <- c(bullets, meaning)\n    return(paste0(\"- \", bullets[1:min(length(bullets), 4)], collapse = \"\\n\") |> paste0(\"\\n\"))\n  }\n\n  num_x <- suppressWarnings(as.numeric(x))\n  finite_x <- num_x[is.finite(num_x)]\n  if (length(finite_x) == 0) {\n    return(\"- No finite values are available, so this variable cannot support a distribution-based business observation.\\n\")\n  }\n\n  missing_share <- mean(is.na(num_x))\n  zero_share <- mean(finite_x == 0)\n  positive_share <- mean(finite_x > 0)\n  median_value <- median(finite_x)\n  mean_value <- mean(finite_x)\n  p95_value <- quantile(finite_x, 0.95, na.rm = TRUE)\n  max_value <- max(finite_x)\n  min_value <- min(finite_x)\n  right_skew <- is.finite(median_value) && abs(mean_value) > abs(median_value) * 2 && p95_value > median_value\n\n  bullets <- c()\n  if (zero_share > 0.50) {\n    bullets <- c(bullets, paste0(\"The distribution is zero-inflated: \", pct(zero_share), \" of finite records are zero, while \", pct(positive_share), \" are positive.\"))\n  } else {\n    bullets <- c(bullets, paste0(\"The centre of the distribution is \", format_profile_value(median_value, var), \", with the 95th percentile at \", format_profile_value(p95_value, var), \".\"))\n  }\n  if (right_skew || max_value > p95_value * 1.5) {\n    bullets <- c(bullets, paste0(\"The upper tail is important: the maximum is \", format_profile_value(max_value, var), \", so averages can be influenced by outliers.\"))\n  }\n  if (missing_share > 0) {\n    bullets <- c(bullets, paste0(\"Missing values account for \", pct(missing_share), \", so this should be treated as a data-quality and segmentation issue.\"))\n  }\n\n  meaning <- case_when(\n    var == \"driver_age\" ~ paste0(\"This age spread means driver-age bands can reveal whether claim frequency is concentrated among younger, middle-aged, or older drivers.\"),\n    var == \"licence_years_held\" ~ paste0(\"This is derived from policy year minus raw `age_driving_licence`, because the original field is a licence-issue year rather than direct tenure; short derived experience should be reviewed with claim frequency.\"),\n    var == \"vehicle_age\" ~ paste0(\"Vehicle-age spread matters because older and newer vehicles can produce different repair-cost and total-loss patterns.\"),\n    var == \"vehicle_value\" ~ paste0(\"The high-value tail indicates severity exposure: expensive vehicles can drive large own-damage or theft losses even if they are not the majority.\"),\n    var == \"power_to_weight_ratio\" ~ paste0(\"This kg-per-horsepower ratio should be read directionally: higher values indicate less power per unit weight, while lower values can indicate more powerful vehicles.\"),\n    var == \"total_premium\" ~ paste0(\"The premium spread shows pricing heterogeneity; high-premium outliers should be compared with incurred losses to check pricing adequacy.\"),\n    var == \"theft_premium\" ~ paste0(\"The zero-versus-positive split shows theft-cover uptake; positive records are the relevant segment for theft-risk enrichment and underwriting review.\"),\n    var == \"glass_premium\" ~ paste0(\"The zero-versus-positive split shows glass-cover uptake; positive records may increase small-claim frequency even when severe-loss risk is limited.\"),\n    var == \"total_claims\" ~ paste0(\"Claim occurrence is rare in the univariate distribution, so volatility analysis should focus on the small positive-claim segment rather than averages alone.\"),\n    var == \"liability_claims\" ~ paste0(\"Liability claims are sparse, so frequency modelling should compare claim occurrence across exposure-adjusted driver, vehicle, and geographic segments.\"),\n    var == \"total_incurred\" ~ paste0(\"Most records have no incurred loss, but the positive tail drives profitability risk; tail-loss monitoring is essential.\"),\n    var == \"liability_injury_incurred\" ~ paste0(\"The injury-cost distribution is sparse but potentially severe, so medical/legal inflation indicators can improve underwriting and reserving judgement.\"),\n    var == \"property_incurred\" ~ paste0(\"The property-loss tail links directly to repair economics, making vehicle age, brand, and parts-cost enrichment useful.\"),\n    var == \"total_exposure\" ~ paste0(\"Exposure measures effective time-on-risk in policy years and ranges from \", format_profile_value(min_value, var), \" to \", format_profile_value(max_value, var), \"; comparisons of claim frequency and loss ratio should control for partial-year and longer-than-one-year policies.\"),\n    TRUE ~ paste0(\"The distribution suggests `\", var, \"` should be reviewed together with claim frequency and incurred severity.\")\n  )\n  bullets <- c(bullets, meaning)\n  paste0(\"- \", bullets[1:min(length(bullets), 4)], collapse = \"\\n\") |> paste0(\"\\n\")\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloss_driver_spec |>\n  select(variable, variable_type, loss_driver_relevance) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|variable                  |variable_type                |loss_driver_relevance                                                                                                                                            |\n|:-------------------------|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|year                      |Time / ordinal categorical   |Portfolio volume and loss experience must be compared against calendar-year mix.                                                                                 |\n|policy_type               |Categorical                  |Coverage structure affects claim exposure and pricing adequacy: TP, TPG, CC, COMP_E, and COMP_N represent increasing breadth of cover.                           |\n|business_type             |Categorical                  |New business (NB) versus portfolio business (P) can show different selection and renewal-risk patterns.                                                          |\n|bonus_score               |Ordinal categorical          |Claim-history quality is a practical underwriting signal: G is favourable, N is neutral, and B is poor claims history.                                           |\n|driver_age                |Numerical                    |Driver age is a core behavioural risk proxy with meaningful distribution spread.                                                                                 |\n|licence_years_held        |Derived numerical            |Raw `age_driving_licence` records the calendar year of licence issue, so years-held is derived for more direct driving-experience interpretation.                |\n|vehicle_age               |Numerical                    |Vehicle age can affect repair economics, safety technology, and claim handling outcomes.                                                                         |\n|vehicle_value             |Numerical money/value        |Vehicle value is directly linked to potential claim severity and sum insured.                                                                                    |\n|power_to_weight_ratio     |Numerical                    |Approximate kg-per-horsepower ratio is a vehicle performance proxy; its direction must be read carefully because higher values imply less power per unit weight. |\n|vehicle_brand             |High-cardinality categorical |Brand can capture differences in repair cost, parts availability, theft attractiveness, and vehicle profile.                                                     |\n|municipality_type         |Categorical                  |Municipality type distinguishes inland (I), coastal (C), and island (IS) contexts that can indicate environmental, road, and claims-service differences.         |\n|circulation_area          |Categorical                  |Urban (U) or rural (R) circulation affects traffic density and accident exposure.                                                                                |\n|total_premium             |Numerical money              |Premium distribution shows price level, product mix, and possible pricing outliers.                                                                              |\n|theft_premium             |Optional premium             |Theft cover uptake indicates where theft exposure is explicitly insured.                                                                                         |\n|glass_premium             |Optional premium             |Glass cover uptake may influence small-claim frequency and optional-coverage behaviour.                                                                          |\n|total_claims              |Count                        |Claim count is the direct frequency outcome for the portfolio.                                                                                                   |\n|liability_claims          |Count                        |Liability claim count is a key third-party frequency driver.                                                                                                     |\n|total_incurred            |Numerical money              |Total incurred cost captures overall severity and tail-loss behaviour.                                                                                           |\n|liability_injury_incurred |Numerical money              |Bodily injury incurred cost is often severe, skewed, and sensitive to legal or medical inflation.                                                                |\n|property_incurred         |Numerical money              |Property incurred cost reflects vehicle repair and damage severity.                                                                                              |\n|total_exposure            |Numerical                    |Exposure records effective time-on-risk in policy years; it usually ranges from 0 to 1 but can exceed 1 for longer contracts.                                    |\n\n\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- The section is intentionally selective: it prioritises variables that can explain loss frequency, severity, exposure, or pricing adequacy.\n- The selected variables follow the data dictionary groups: policy and insured characteristics, driver and vehicle characteristics, premiums, and exposure/claims/incurred outcomes.\n- Coded categorical variables are interpreted explicitly: `policy_type` captures coverage breadth, `bonus_score` captures prior claims quality, `payment_frequency` captures billing pattern, and `circulation_area` captures urban/rural driving context.\n- External enrichment is most relevant for geography, vehicle brand, vehicle value, theft risk, repair-cost inflation, traffic density, weather, and injury-cost inflation.\n:::\n\n**Focused univariate profiles for selected loss-driver variables**\n\n\n```{.r .cell-code}\nfor (i in seq_len(nrow(loss_driver_spec))) {\n  spec_row <- loss_driver_spec[i, ]\n  var <- spec_row$variable\n  family <- spec_row$visual_family\n\n  cat(\"\\n\\n**`\", var, \"`**  \\n\", sep = \"\")\n  cat(\"Variable type: \", spec_row$variable_type, \"  \\n\", sep = \"\")\n  print(profile_summary(motor_profile, var, family) |> kable())\n  cat(\"\\n\\n\")\n\n  if (var %in% density_estimation_vars) {\n    cat(\"*Individual visualisation omitted because this variable is included in the cross-component density estimation below.*\\n\\n\")\n  } else {\n    print(make_profile_visual(motor_profile, spec_row))\n    cat(\"\\n\\n\")\n  }\n\n  cat(\"::: {.observation-box}\\n\")\n  cat(\"**Observations**\\n\\n\")\n  cat(profile_observations(motor_profile, spec_row))\n  cat(\":::\\n\\n\")\n}\n```\n\n\n\n**`year`**  \nVariable type: Time / ordinal categorical  \n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |3     |\n|Top category                |2024  |\n|Top-category share          |47.5% |\n\n\n\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is led by `2024`, representing 47.5% of non-missing records.\n- The variable has enough category spread to support segment comparison in the bivariate loss-ratio analysis.\n- This year mix matters because any heavier concentration in `2024` can influence observed premium growth, claim emergence, and inflation effects.\n:::\n\n\n\n**`policy_type`**  \nVariable type: Categorical  \n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |5     |\n|Top category                |CC    |\n|Top-category share          |57.8% |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-1.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is led by `CC`, representing 57.8% of non-missing records.\n- The variable has enough category spread to support segment comparison in the bivariate loss-ratio analysis.\n- Policy type records coverage breadth: TP is basic third-party, TPG adds glass, CC combines third-party with additional covers, COMP_E is comprehensive with excess, and COMP_N is comprehensive without excess; because `CC` is largest, product mix must be controlled before interpreting loss differences.\n:::\n\n\n\n**`business_type`**  \nVariable type: Categorical  \n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |2     |\n|Top category                |NB    |\n|Top-category share          |69.3% |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-2.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is led by `NB`, representing 69.3% of non-missing records.\n- The variable has enough category spread to support segment comparison in the bivariate loss-ratio analysis.\n- Business type separates new business (NB) from portfolio business (P); the dominant `NB` mix affects whether observed risk is mainly renewal exposure or new-selection risk.\n:::\n\n\n\n**`bonus_score`**  \nVariable type: Ordinal categorical  \n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |3     |\n|Top category                |G     |\n|Top-category share          |96.4% |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-3.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is led by `G`, representing 96.4% of non-missing records.\n- The concentration in one category means aggregate portfolio results may be strongly shaped by this dominant segment.\n- Bonus score maps claim-history quality where G is favourable, N is neutral, and B is poor; this makes the variable a direct prior-claims signal for later claim-frequency comparison.\n:::\n\n\n\n**`driver_age`**  \nVariable type: Numerical  \n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |18    |\n|Median          |48    |\n|Mean            |49    |\n|95th percentile |69    |\n|Maximum         |90    |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-4.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is 48, with the 95th percentile at 69.\n- This age spread means driver-age bands can reveal whether claim frequency is concentrated among younger, middle-aged, or older drivers.\n:::\n\n\n\n**`licence_years_held`**  \nVariable type: Derived numerical  \n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |2     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |1,944 |\n|Median          |2,003 |\n|Mean            |2,000 |\n|95th percentile |2,006 |\n|Maximum         |2,024 |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-5.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is 2,003, with the 95th percentile at 2,006.\n- Missing values account for 0.0%, so this should be treated as a data-quality and segmentation issue.\n- This is derived from policy year minus raw `age_driving_licence`, because the original field is a licence-issue year rather than direct tenure; short derived experience should be reviewed with claim frequency.\n:::\n\n\n\n**`vehicle_age`**  \nVariable type: Numerical  \n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |2     |\n|Missing share   |0.0%  |\n|Zero share      |0.1%  |\n|Minimum         |0     |\n|Median          |25    |\n|Mean            |26    |\n|95th percentile |46    |\n|Maximum         |68    |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-6.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is 25, with the 95th percentile at 46.\n- Missing values account for 0.0%, so this should be treated as a data-quality and segmentation issue.\n- Vehicle-age spread matters because older and newer vehicles can produce different repair-cost and total-loss patterns.\n:::\n\n\n\n**`vehicle_value`**  \nVariable type: Numerical money/value  \n\n\n|metric          |value    |\n|:---------------|:--------|\n|Missing records |513      |\n|Missing share   |0.1%     |\n|Zero share      |0.0%     |\n|Minimum         |€1,630   |\n|Median          |€24,730  |\n|Mean            |€26,977  |\n|95th percentile |€49,361  |\n|Maximum         |€374,034 |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-7.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is €24,730, with the 95th percentile at €49,361.\n- The upper tail is important: the maximum is €374,034, so averages can be influenced by outliers.\n- Missing values account for 0.1%, so this should be treated as a data-quality and segmentation issue.\n- The high-value tail indicates severity exposure: expensive vehicles can drive large own-damage or theft losses even if they are not the majority.\n:::\n\n\n\n**`power_to_weight_ratio`**  \nVariable type: Numerical  \n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |0     |\n|Median          |12    |\n|Mean            |12    |\n|95th percentile |17    |\n|Maximum         |65    |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-8.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is 12, with the 95th percentile at 17.\n- The upper tail is important: the maximum is 65, so averages can be influenced by outliers.\n- This kg-per-horsepower ratio should be read directionally: higher values indicate less power per unit weight, while lower values can indicate more powerful vehicles.\n:::\n\n\n\n**`vehicle_brand`**  \nVariable type: High-cardinality categorical  \n\n\n|metric                      |value   |\n|:---------------------------|:-------|\n|Missing records             |0       |\n|Missing share               |0.0%    |\n|Distinct non-missing values |68      |\n|Top category                |RENAULT |\n|Top-category share          |9.7%    |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-9.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is led by `RENAULT`, representing 9.7% of non-missing records.\n- There are 68 distinct values, so interpretation should focus on the leading groups and not over-read rare categories.\n- Brand concentration can hide repair-cost, theft, and parts-availability differences; top brands are good candidates for enrichment with market repair-cost and theft-rate data.\n:::\n\n\n\n**`municipality_type`**  \nVariable type: Categorical  \n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |3     |\n|Top category                |I     |\n|Top-category share          |64.6% |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-10.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is led by `I`, representing 64.6% of non-missing records.\n- The variable has enough category spread to support segment comparison in the bivariate loss-ratio analysis.\n- Municipality type separates inland (I), coastal (C), and island (IS) contexts; the dominant `I` context should be considered when enriching with weather, road-density, flood, or local economic indicators.\n:::\n\n\n\n**`circulation_area`**  \nVariable type: Categorical  \n\n\n|metric                      |value |\n|:---------------------------|:-----|\n|Missing records             |0     |\n|Missing share               |0.0%  |\n|Distinct non-missing values |2     |\n|Top category                |U     |\n|Top-category share          |53.8% |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-11.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is led by `U`, representing 53.8% of non-missing records.\n- The variable has enough category spread to support segment comparison in the bivariate loss-ratio analysis.\n- Circulation area separates urban (U) from rural (R) exposure; the `U` pattern should be compared with claim frequency and severity, not only record count.\n:::\n\n\n\n**`total_premium`**  \nVariable type: Numerical money  \n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |0.0%   |\n|Minimum         |€0     |\n|Median          |€258   |\n|Mean            |€297   |\n|95th percentile |€705   |\n|Maximum         |€5,108 |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-12.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is €258, with the 95th percentile at €705.\n- The upper tail is important: the maximum is €5,108, so averages can be influenced by outliers.\n- The premium spread shows pricing heterogeneity; high-premium outliers should be compared with incurred losses to check pricing adequacy.\n:::\n\n\n\n**`theft_premium`**  \nVariable type: Optional premium  \n\n\n|metric          |value  |\n|:---------------|:------|\n|Missing records |0      |\n|Missing share   |0.0%   |\n|Zero share      |11.9%  |\n|Minimum         |€0     |\n|Median          |€6     |\n|Mean            |€11    |\n|95th percentile |€39    |\n|Maximum         |€1,047 |\n\n\n*Individual visualisation omitted because this variable is included in the cross-component density estimation below.*\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is €6, with the 95th percentile at €39.\n- The upper tail is important: the maximum is €1,047, so averages can be influenced by outliers.\n- The zero-versus-positive split shows theft-cover uptake; positive records are the relevant segment for theft-risk enrichment and underwriting review.\n:::\n\n\n\n**`glass_premium`**  \nVariable type: Optional premium  \n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |1.6%  |\n|Minimum         |€0    |\n|Median          |€15   |\n|Mean            |€19   |\n|95th percentile |€52   |\n|Maximum         |€388  |\n\n\n*Individual visualisation omitted because this variable is included in the cross-component density estimation below.*\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is €15, with the 95th percentile at €52.\n- The upper tail is important: the maximum is €388, so averages can be influenced by outliers.\n- The zero-versus-positive split shows glass-cover uptake; positive records may increase small-claim frequency even when severe-loss risk is limited.\n:::\n\n\n\n**`total_claims`**  \nVariable type: Count  \n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |85.7% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |1     |\n|Maximum         |18    |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-13.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is zero-inflated: 85.7% of finite records are zero, while 14.3% are positive.\n- The upper tail is important: the maximum is 18, so averages can be influenced by outliers.\n- Claim occurrence is rare in the univariate distribution, so volatility analysis should focus on the small positive-claim segment rather than averages alone.\n:::\n\n\n\n**`liability_claims`**  \nVariable type: Count  \n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |91.3% |\n|Minimum         |0     |\n|Median          |0     |\n|Mean            |0     |\n|95th percentile |1     |\n|Maximum         |8     |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-14.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is zero-inflated: 91.3% of finite records are zero, while 8.7% are positive.\n- The upper tail is important: the maximum is 8, so averages can be influenced by outliers.\n- Liability claims are sparse, so frequency modelling should compare claim occurrence across exposure-adjusted driver, vehicle, and geographic segments.\n:::\n\n\n\n**`total_incurred`**  \nVariable type: Numerical money  \n\n\n|metric          |value    |\n|:---------------|:--------|\n|Missing records |0        |\n|Missing share   |0.0%     |\n|Zero share      |88.1%    |\n|Minimum         |€0       |\n|Median          |€0       |\n|Mean            |€209     |\n|95th percentile |€1,055   |\n|Maximum         |€571,128 |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-15.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is zero-inflated: 88.1% of finite records are zero, while 11.9% are positive.\n- The upper tail is important: the maximum is €571,128, so averages can be influenced by outliers.\n- Most records have no incurred loss, but the positive tail drives profitability risk; tail-loss monitoring is essential.\n:::\n\n\n\n**`liability_injury_incurred`**  \nVariable type: Numerical money  \n\n\n|metric          |value    |\n|:---------------|:--------|\n|Missing records |0        |\n|Missing share   |0.0%     |\n|Zero share      |98.7%    |\n|Minimum         |€0       |\n|Median          |€0       |\n|Mean            |€68      |\n|95th percentile |€0       |\n|Maximum         |€560,026 |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-16.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is zero-inflated: 98.7% of finite records are zero, while 1.3% are positive.\n- The upper tail is important: the maximum is €560,026, so averages can be influenced by outliers.\n- The injury-cost distribution is sparse but potentially severe, so medical/legal inflation indicators can improve underwriting and reserving judgement.\n:::\n\n\n\n**`property_incurred`**  \nVariable type: Numerical money  \n\n\n|metric          |value   |\n|:---------------|:-------|\n|Missing records |0       |\n|Missing share   |0.0%    |\n|Zero share      |96.5%   |\n|Minimum         |€0      |\n|Median          |€0      |\n|Mean            |€53     |\n|95th percentile |€0      |\n|Maximum         |€27,542 |\n\n\n*Individual visualisation omitted because this variable is included in the cross-component density estimation below.*\n\n::: {.observation-box}\n**Observations**\n\n- The distribution is zero-inflated: 96.5% of finite records are zero, while 3.5% are positive.\n- The upper tail is important: the maximum is €27,542, so averages can be influenced by outliers.\n- The property-loss tail links directly to repair economics, making vehicle age, brand, and parts-cost enrichment useful.\n:::\n\n\n\n**`total_exposure`**  \nVariable type: Numerical  \n\n\n|metric          |value |\n|:---------------|:-----|\n|Missing records |0     |\n|Missing share   |0.0%  |\n|Zero share      |0.0%  |\n|Minimum         |0     |\n|Median          |1     |\n|Mean            |1     |\n|95th percentile |1     |\n|Maximum         |1     |\n\n\n![](TH_Ex1_report_files/figure-html/selected-loss-driver-profiles-17.png){width=864}\n\n::: {.observation-box}\n**Observations**\n\n- The centre of the distribution is 1, with the 95th percentile at 1.\n- Exposure measures effective time-on-risk in policy years and ranges from 0 to 1; comparisons of claim frequency and loss ratio should control for partial-year and longer-than-one-year policies.\n:::\n\n### Cross-component ridgeline density plots\n\nThe following ridgeline density plots are placed after the individual univariate profiles so they can be read as a cross-variable comparison rather than as replacements for the single-variable diagnostics above.\n\n#### Premium components\n\nAll finite values are shown. Density estimation and the x-axis are forced to start at 0; the upper x-axis is capped at the 99th percentile for readability because premium amounts are right-skewed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmanual_ridgeline(\n  motor,\n  premium_component_vars,\n  title = \"Ridgeline density plot of premium components\",\n  cap_quantile = 0.99,\n  x_labels = money,\n  x_axis_title = \"Premium amount, capped at 99th percentile\"\n)\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_files/figure-html/premium-components-ridgeline-1.png){width=864}\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- The premium variables represent coverage-specific charges that sum to `total_premium`, so the ridges show how pricing is distributed across the liability, property damage, theft, fire, glass, legal protection, and occupants covers.\n- `liability_premium` is charged on every record and forms the main baseline premium component.\n- `property_damage_premium` is structurally different: about 69.1% of records are zero, so its ridge mainly separates policies with and without that cover.\n- The smaller components, especially `fire_premium`, `legal_protection_premium`, and `occupants_premium`, sit at much lower premium levels, while `theft_premium` has a longer upper tail.\n- The plot is useful for comparing premium scale before checking whether high-premium coverage components are matched by incurred-loss experience.\n:::\n\n#### Optional premiums\n\nPositive premium values only; zero values are excluded to compare purchased optional covers. Density estimation and the x-axis are forced to start at 0, with the upper x-axis capped at the 99th percentile for readability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmanual_ridgeline(\n  motor,\n  optional_premium_vars,\n  title = \"Ridgeline density plot of optional premium components\",\n  positive_only = TRUE,\n  cap_quantile = 0.99,\n  x_labels = money,\n  x_axis_title = \"Positive premium amount, capped at 99th percentile\"\n)\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_files/figure-html/optional-premiums-ridgeline-1.png){width=864}\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- Removing zero values makes optional-cover pricing patterns comparable only among policies where theft, fire, glass, legal protection, or occupants coverage was purchased or charged.\n- `glass_premium` has broad uptake and a visibly higher positive premium distribution than `fire_premium` and `occupants_premium`.\n- `theft_premium` is generally small for most positive records but has a long right tail, suggesting that some theft-covered policies carry materially higher theft pricing.\n- This view should be paired with the zero-versus-positive charts above, because optional-cover uptake and positive premium amount answer different business questions.\n:::\n\n#### Incurred claim costs\n\nPositive incurred values only. Density is estimated on `log10(value + 1)` so the transformed density and x-axis can start at 0 while still making small and severe claims comparable in one view.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmanual_ridgeline(\n  motor,\n  incurred_component_vars,\n  title = \"Ridgeline density plot of incurred claim costs\",\n  positive_only = TRUE,\n  log10_x = TRUE,\n  x_labels = money,\n  x_axis_title = \"Positive incurred cost, log10(value + 1) scale\"\n)\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_files/figure-html/incurred-costs-ridgeline-1.png){width=864}\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- The incurred variables represent paid plus reserved claim costs by coverage; most policy-year records are zero because no claim was reported during the exposure period.\n- `liability_incurred` and `property_incurred` have the largest positive-claim shares, while theft, fire, legal protection, and occupants incurred costs are rare.\n- The log scale is necessary because positive claim costs range from small claims to severe tail losses.\n- `liability_incurred` has the most important upper-tail risk, so liability cost should be prioritised in later profitability and volatility checks.\n- The ridgeline plot confirms that claim severity is driven by the small positive-loss subset, not by the majority of zero-claim policy records.\n:::\n\n## Task 2: Bivariate visual analytics and validation\n\nBivariate analysis compares profitability and volatility across time and major risk-related segments. It builds on the Section 3 finding that the portfolio is zero-inflated at policy level but exposed to a small positive-loss tail, especially through `liability_incurred` and other incurred-cost components. The comparisons use the data dictionary meaning of each segment: coverage structure, claims-history quality, billing frequency, fuel type, circulation area, driver/vehicle characteristics, and exposure-adjusted claim outcomes.\n\n### Temporal trend: profitability worsens in 2024\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyearly <- portfolio_summary(motor, year)\nkable(yearly, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|year | records|  exposure|  premium| incurred| claims|   profit| high_loss_rate| p95_loss_ratio| loss_ratio| claim_frequency| avg_premium| avg_severity|\n|:----|-------:|---------:|--------:|--------:|------:|--------:|--------------:|--------------:|----------:|---------------:|-----------:|------------:|\n|2022 |   67172|  41912.50| 18697928| 12270105|  12665|  6427823|          0.080|          2.419|      0.656|           0.302|     446.118|      968.820|\n|2023 |  118835|  82399.04| 35344308| 23488354|  25158| 11855954|          0.087|          2.744|      0.665|           0.305|     428.941|      933.634|\n|2024 |  168133| 126014.36| 51037433| 38106351|  39276| 12931082|          0.097|          3.205|      0.747|           0.312|     405.013|      970.220|\n\n\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- The year-level table uses `year` as the calendar-year policy period and provides the numeric baseline for exposure, premium, incurred loss, profit, claim frequency, and loss ratio.\n- Aggregate loss ratio rises from 65.6% in 2022 to 66.5% in 2023 and 74.7% in 2024, showing a clear deterioration in underwriting profitability.\n- Claim frequency also rises slightly from 0.302 to 0.312, while the high-loss policy share increases from 8.0% to 9.7%.\n- This pattern links the Section 3 positive-loss tail to a time trend: 2024 is not only larger in exposure, but also more loss-heavy.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrend_amount_df <- yearly |>\n  select(year, Premium = premium, Incurred = incurred, Profit = profit) |>\n  pivot_longer(-year, names_to = \"measure\", values_to = \"amount\") |>\n  mutate(hover = paste0(\n    \"Year: \", year,\n    \"<br>Measure: \", measure,\n    \"<br>Amount: \", money(amount)\n  ))\n\ntrend_amount <- trend_amount_df |>\n  ggplot(aes(x = year, y = amount, colour = measure, group = measure, text = hover)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  scale_y_continuous(labels = money) +\n  labs(\n    title = \"Premium, incurred loss, and profit by year\",\n    x = NULL,\n    y = \"Aggregate amount\"\n  )\n\ntrend_lr_df <- yearly |>\n  mutate(hover = paste0(\n    \"Year: \", year,\n    \"<br>Loss ratio: \", pct(loss_ratio)\n  ))\n\ntrend_lr <- trend_lr_df |>\n  ggplot(aes(x = year, y = loss_ratio, group = 1, text = hover)) +\n  geom_line(linewidth = 1, colour = \"#d95f0e\") +\n  geom_point(size = 3, colour = \"#d95f0e\") +\n  scale_y_continuous(labels = pct) +\n  labs(\n    title = \"Aggregate loss ratio by year\",\n    x = NULL,\n    y = \"Loss ratio\"\n  )\n\nsubplot(\n  ggplotly(trend_amount, tooltip = \"text\"),\n  ggplotly(trend_lr, tooltip = \"text\"),\n  widths = c(0.58, 0.42),\n  margin = 0.06,\n  titleX = TRUE,\n  titleY = TRUE\n) |>\n  layout(legend = list(orientation = \"h\", x = 0, y = -0.2))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-36d7b243dfa8821c3265\" style=\"width:100%;height:295px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-36d7b243dfa8821c3265\">{\"x\":{\"data\":[{\"x\":[1,2,3],\"y\":[12270105.055,23488354.353999998,38106351.280000001],\"text\":[\"Year: 2022<br>Measure: Incurred<br>Amount: €12,270,105\",\"Year: 2023<br>Measure: Incurred<br>Amount: €23,488,354\",\"Year: 2024<br>Measure: Incurred<br>Amount: €38,106,351\"],\"type\":\"scatter\",\"mode\":\"lines+markers\",\"line\":{\"width\":3.7795275590551185,\"color\":\"rgba(248,118,109,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Incurred\",\"legendgroup\":\"Incurred\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\"}},\"frame\":null},{\"x\":[1,2,3],\"y\":[18697928.342009425,35344308.084516324,51037433.000661492],\"text\":[\"Year: 2022<br>Measure: Premium<br>Amount: €18,697,928\",\"Year: 2023<br>Measure: Premium<br>Amount: €35,344,308\",\"Year: 2024<br>Measure: Premium<br>Amount: €51,037,433\"],\"type\":\"scatter\",\"mode\":\"lines+markers\",\"line\":{\"width\":3.7795275590551185,\"color\":\"rgba(0,186,56,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Premium\",\"legendgroup\":\"Premium\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,186,56,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,186,56,1)\"}},\"frame\":null},{\"x\":[1,2,3],\"y\":[6427823.2870094264,11855953.730516324,12931081.720661495],\"text\":[\"Year: 2022<br>Measure: Profit<br>Amount: €6,427,823\",\"Year: 2023<br>Measure: Profit<br>Amount: €11,855,954\",\"Year: 2024<br>Measure: Profit<br>Amount: €12,931,082\"],\"type\":\"scatter\",\"mode\":\"lines+markers\",\"line\":{\"width\":3.7795275590551185,\"color\":\"rgba(97,156,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Profit\",\"legendgroup\":\"Profit\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(97,156,255,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(97,156,255,1)\"}},\"frame\":null},{\"x\":[1,2,3],\"y\":[0.65622805000446149,0.66455832995326913,0.74663534272004051],\"text\":[\"Year: 2022<br>Loss ratio: 65.6%\",\"Year: 2023<br>Loss ratio: 66.5%\",\"Year: 2024<br>Loss ratio: 74.7%\"],\"type\":\"scatter\",\"mode\":\"lines+markers\",\"line\":{\"width\":3.7795275590551185,\"color\":\"rgba(217,95,14,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(217,95,14,1)\",\"opacity\":1,\"size\":11.338582677165356,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(217,95,14,1)\"}},\"frame\":null}],\"layout\":{\"xaxis\":{\"domain\":[0,0.52000000000000002],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,3.6000000000000001],\"tickmode\":\"array\",\"ticktext\":[\"2022\",\"2023\",\"2024\"],\"tickvals\":[1,2,3],\"categoryorder\":\"array\",\"categoryarray\":[\"2022\",\"2023\",\"2024\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"xaxis2\":{\"domain\":[0.6399999999999999,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,3.6000000000000001],\"tickmode\":\"array\",\"ticktext\":[\"2022\",\"2023\",\"2024\"],\"tickvals\":[1,2,3],\"categoryorder\":\"array\",\"categoryarray\":[\"2022\",\"2023\",\"2024\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y2\",\"title\":{\"text\":\"\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis2\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.65170768536868251,0.75115570735581949],\"tickmode\":\"array\",\"ticktext\":[\"67.5%\",\"70.0%\",\"72.5%\",\"75.0%\"],\"tickvals\":[0.67500000000000004,0.70000000000000007,0.72500000000000009,0.75],\"categoryorder\":\"array\",\"categoryarray\":[\"67.5%\",\"70.0%\",\"72.5%\",\"75.0%\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505603,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x2\",\"title\":{\"text\":\"Loss ratio\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[4197342.8013268225,53267913.486344099],\"tickmode\":\"array\",\"ticktext\":[\"€10,000,000\",\"€20,000,000\",\"€30,000,000\",\"€40,000,000\",\"€50,000,000\"],\"tickvals\":[10000000,20000000,30000000,40000000,50000000],\"categoryorder\":\"array\",\"categoryarray\":[\"€10,000,000\",\"€20,000,000\",\"€30,000,000\",\"€40,000,000\",\"€50,000,000\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505603,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Aggregate amount\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"annotations\":[],\"shapes\":[],\"images\":[],\"margin\":{\"t\":43.098381070983812,\"r\":7.9701120797011207,\"b\":24.707347447073481,\"l\":59.775840597758425},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"Aggregate loss ratio by year\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":19.128268991282692},\"x\":0,\"xref\":\"paper\"},\"showlegend\":false,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"title\":{\"text\":\"measure\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"orientation\":\"h\",\"x\":0,\"y\":-0.20000000000000001},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"attrs\":{\"f88c45022458\":{\"x\":{},\"y\":{},\"colour\":{},\"text\":{},\"type\":\"scatter\"},\"f88c4f857e22\":{\"x\":{},\"y\":{},\"colour\":{},\"text\":{}},\"f88c2d755ccf\":{\"x\":{},\"y\":{},\"text\":{},\"type\":\"scatter\"},\"f88c1dcf44db\":{\"x\":{},\"y\":{},\"text\":{}}},\"source\":\"A\",\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"subplot\":true,\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- Premium and incurred losses both increase over time, but incurred losses grow faster in 2024.\n- Aggregate profit remains positive, so the issue is not absolute loss-making at portfolio level; the issue is a weaker margin.\n- The right-hand loss-ratio panel makes the deterioration easier to see than the amount plot alone because it standardises incurred loss against premium.\n- The visual signal supports treating 2024 as an early-warning period for deeper segment checks.\n:::\n\n### Policy type: comprehensive covers carry higher risk\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_tbl <- portfolio_summary(motor, policy_type) |>\n  arrange(desc(loss_ratio))\n\nkable(policy_tbl, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|policy_type | records|   exposure|  premium|   incurred| claims|     profit| high_loss_rate| p95_loss_ratio| loss_ratio| claim_frequency| avg_premium| avg_severity|\n|:-----------|-------:|----------:|--------:|----------:|------:|----------:|--------------:|--------------:|----------:|---------------:|-----------:|------------:|\n|COMP_N      |   16181|  12342.351| 10344550|  9709280.8|  12907|   635269.3|          0.208|          4.546|      0.939|           1.046|     838.135|      752.249|\n|COMP_E      |   91199|  65040.337| 35712392| 26367075.6|  26687|  9345316.3|          0.116|          3.335|      0.738|           0.410|     549.081|      988.012|\n|TPG         |   36367|  24905.351|  8201409|  5671461.2|   5156|  2529947.8|          0.070|          2.235|      0.692|           0.207|     329.303|     1099.973|\n|CC          |  204636| 144235.186| 49801769| 31563558.5|  31842| 18238210.8|          0.074|          2.497|      0.634|           0.221|     345.282|      991.256|\n|TP          |    5757|   3802.674|  1019549|   553434.5|    507|   466114.6|          0.047|          0.177|      0.543|           0.133|     268.114|     1091.587|\n\n\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- The policy-type table ranks coverage structures by aggregate loss ratio and separates product profitability from individual policy-year spread.\n- `COMP_N` means comprehensive without excess and has the weakest aggregate result with a 93.9% loss ratio; `COMP_E` means comprehensive with excess and follows at 73.8%.\n- `COMP_N` also has the highest claim frequency at about 1.046 claims per exposure unit and the highest high-loss policy share at 20.8%, consistent with broader first-party coverage exposure.\n- This aligns with Section 3's incurred-cost observation: profitability pressure is driven by claim occurrence and tail losses rather than by premium distribution alone.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverall_loss_ratio <- sum(motor$total_incurred, na.rm = TRUE) / sum(motor$total_premium, na.rm = TRUE)\n\npolicy_lr <- policy_tbl |>\n  mutate(\n    policy_type = fct_reorder(policy_type, loss_ratio),\n    label = paste0(pct(loss_ratio), \" | exp \", comma(round(exposure)))\n  ) |>\n  ggplot(aes(x = loss_ratio, y = policy_type)) +\n  geom_vline(xintercept = overall_loss_ratio, linewidth = 0.8, colour = \"#08519c\") +\n  geom_vline(xintercept = 1, linetype = \"dashed\", linewidth = 0.8, colour = \"red\") +\n  geom_segment(aes(x = overall_loss_ratio, xend = loss_ratio, yend = policy_type), colour = \"grey75\") +\n  geom_point(aes(size = exposure), colour = \"#08519c\", alpha = 0.82) +\n  geom_text(aes(label = label), hjust = -0.08, size = 3.1) +\n  scale_x_continuous(\n    labels = pct,\n    limits = c(0, max(policy_tbl$loss_ratio, overall_loss_ratio, 1, na.rm = TRUE) * 1.28)\n  ) +\n  scale_size_continuous(labels = comma, range = c(3, 8)) +\n  coord_cartesian(clip = \"off\") +\n  labs(\n    title = \"Aggregate loss ratio by policy type\",\n    subtitle = \"Blue line marks the overall portfolio loss ratio; red dashed line marks 100% break-even before expenses.\",\n    x = \"Aggregate loss ratio\",\n    y = NULL,\n    size = \"Exposure\"\n  ) +\n  theme(plot.margin = margin(5.5, 35, 5.5, 5.5))\n\npolicy_box <- motor |>\n  filter(!is.na(policy_type), !is.na(loss_ratio_cap)) |>\n  ggplot(aes(x = fct_reorder(policy_type, loss_ratio_cap, .fun = median), y = loss_ratio_cap)) +\n  geom_boxplot(fill = \"#9ecae1\", outlier.alpha = 0.06) +\n  coord_flip() +\n  scale_y_continuous(labels = pct) +\n  labs(\n    title = \"Spread of capped individual loss ratio\",\n    subtitle = \"Capping exposes group spread without letting extreme outliers dominate.\",\n    x = NULL,\n    y = \"Capped individual loss ratio\"\n  )\n\npolicy_lr + policy_box\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_files/figure-html/unnamed-chunk-10-1.png){width=1056}\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- `COMP_N` and `COMP_E` are the main policy-type segments requiring closer monitoring because they represent comprehensive cover, with and without excess respectively.\n- Most policy-year records still have zero or low individual loss ratios, so the boxplot does not suggest that every comprehensive-cover policy performs poorly.\n- Weak segment performance is concentrated in claim frequency and upper-tail loss outcomes, consistent with the zero-inflated distributions observed in Section 3.\n- The dot plot compares each policy type with the overall portfolio loss ratio and the 100% break-even line, while the labels show both percentage loss ratio and total exposure.\n:::\n\n### Segment scan: bonus score, fuel type, and circulation area\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverall_loss_ratio <- sum(motor$total_incurred, na.rm = TRUE) / sum(motor$total_premium, na.rm = TRUE)\n\nseg_long <- bind_rows(\n  portfolio_summary(motor, bonus_score) |>\n    mutate(segment = \"Bonus score\", category = as.character(bonus_score)),\n  portfolio_summary(motor, fuel_type) |>\n    mutate(segment = \"Fuel type\", category = fct_na_value_to_level(as.factor(fuel_type), \"Missing\") |> as.character()),\n  portfolio_summary(motor, circulation_area) |>\n    mutate(segment = \"Circulation area\", category = as.character(circulation_area)),\n  portfolio_summary(motor, payment_frequency) |>\n    mutate(segment = \"Payment frequency\", category = as.character(payment_frequency))\n)\n\nseg_long |>\n  mutate(\n    category = fct_reorder(category, loss_ratio),\n    label = paste0(pct(loss_ratio), \" | exp \", comma(round(exposure)))\n  ) |>\n  ggplot(aes(x = loss_ratio, y = category)) +\n  geom_vline(xintercept = overall_loss_ratio, linewidth = 0.8, colour = \"#08519c\") +\n  geom_vline(xintercept = 1, linetype = \"dashed\", linewidth = 0.8, colour = \"red\") +\n  geom_segment(aes(x = overall_loss_ratio, xend = loss_ratio, yend = category), colour = \"grey75\") +\n  geom_point(aes(size = exposure, colour = segment), alpha = 0.82, show.legend = FALSE) +\n  geom_text(aes(label = label), hjust = -0.05, size = 2.7, show.legend = FALSE) +\n  scale_x_continuous(\n    labels = pct,\n    limits = c(0, max(seg_long$loss_ratio, overall_loss_ratio, 1, na.rm = TRUE) * 1.30)\n  ) +\n  scale_size_continuous(labels = comma, range = c(2.8, 7.5)) +\n  facet_wrap(~ segment, scales = \"free_y\") +\n  coord_cartesian(clip = \"off\") +\n  labs(\n    title = \"Loss ratio differs across risk-related categories\",\n    subtitle = \"Blue line marks the overall portfolio loss ratio; red dashed line marks 100% break-even before expenses.\",\n    x = \"Aggregate loss ratio\",\n    y = NULL,\n    size = \"Exposure\"\n  ) +\n  theme(plot.margin = margin(5.5, 55, 5.5, 5.5))\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_files/figure-html/unnamed-chunk-11-1.png){width=1056}\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- Non-good bonus scores show weaker experience: neutral `N` and poor-history `B` have loss ratios of about 81.4% and 79.0%, compared with 69.7% for favourable-history `G`.\n- Diesel vehicles (`D`) have a higher loss ratio than gasoline vehicles (`G`), about 73.0% versus 64.3%.\n- Urban circulation areas (`U`) have a higher loss ratio than rural areas (`R`), about 71.4% versus 68.9%.\n- Semi-annual (`S`) and quarterly (`Q`) payment frequencies have higher loss ratios than annual (`A`) payment, so billing pattern is a useful screening variable.\n- The dot-plot labels add total exposure, making it easier to separate materially important categories from small or sparse categories.\n- These visual signals are not causal by themselves because exposure, product mix, vehicle profile, and policy type can differ across segments.\n:::\n\n### Policy type by year heatmap\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor |>\n  group_by(year, policy_type) |>\n  summarise(\n    exposure = sum(total_exposure, na.rm = TRUE),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    loss_ratio = incurred / premium,\n    .groups = \"drop\"\n  ) |>\n  ggplot(aes(x = year, y = policy_type, fill = loss_ratio)) +\n  geom_tile(colour = \"white\") +\n  geom_text(aes(label = pct(loss_ratio)), colour = \"white\", fontface = \"bold\") +\n  scale_fill_gradient(low = \"#2c7fb8\", high = \"#d7301f\", labels = pct) +\n  labs(\n    title = \"Loss-ratio heatmap by year and policy type\",\n    subtitle = \"Darker red cells identify combinations needing closer monitoring.\",\n    x = NULL,\n    y = NULL,\n    fill = \"Loss ratio\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_Ex1_report_files/figure-html/unnamed-chunk-12-1.png){width=864}\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- The heatmap links the year-level deterioration with policy-type differences.\n- `COMP_N`, comprehensive without excess, is the clearest 2024 hotspot, with a loss ratio slightly above break-even at about 102.4%.\n- `COMP_N` worsens from 72.8% in 2022 to 92.3% in 2023 and 102.4% in 2024, suggesting persistent deterioration rather than a one-year isolated cell.\n- `COMP_E`, comprehensive with excess, also rises in 2024, reinforcing that comprehensive-cover segments should be monitored separately from third-party-focused covers such as TP and TPG.\n:::\n\n### Brand-level volatility screen\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrand_tbl <- motor |>\n  group_by(vehicle_brand) |>\n  summarise(\n    records = n(),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    premium = sum(total_premium, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    high_loss_rate = mean(loss_ratio > 1, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  filter(exposure >= 1000) |>\n  mutate(hover = paste0(\n    \"Brand: \", vehicle_brand,\n    \"<br>Exposure: \", comma(exposure),\n    \"<br>Claim frequency: \", number(claim_frequency, accuracy = 0.01),\n    \"<br>Loss ratio: \", pct(loss_ratio),\n    \"<br>Premium: \", money(premium),\n    \"<br>Incurred: \", money(incurred),\n    \"<br>Claims: \", comma(claims)\n  ))\n\nbrand_volatility_plot <- brand_tbl |>\n  ggplot(aes(x = claim_frequency, y = loss_ratio, size = exposure, text = hover)) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", colour = \"red\") +\n  geom_point(alpha = 0.65, colour = \"#08519c\") +\n  geom_text_repel(\n    data = brand_tbl |> slice_max(loss_ratio, n = 8),\n    aes(label = vehicle_brand),\n    size = 3,\n    max.overlaps = 20\n  ) +\n  scale_x_continuous(labels = number_format(accuracy = 0.01)) +\n  scale_y_continuous(labels = pct) +\n  scale_size_continuous(labels = comma, range = c(2, 12)) +\n  labs(\n    title = \"Brand-level screen for high loss ratio and claim frequency\",\n    subtitle = \"Only brands with exposure >= 1,000 are shown.\",\n    x = \"Claim frequency\",\n    y = \"Aggregate loss ratio\",\n    size = \"Exposure\"\n  )\n\nggplotly(brand_volatility_plot, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-896f70ab7be15480f0b9\" style=\"width:100%;height:390px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-896f70ab7be15480f0b9\">{\"x\":{\"data\":[{\"x\":[0.1634986528698576,0.47043753883305356],\"y\":[1,1],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.30619244622651126,0.40548054568994379,0.45648577128927192,0.28946150572990703,0.27709154397672536,0.33107580776635043,0.19029650430509384,0.26304185711054734,0.29423453838733848,0.35641028261708751,0.3108186568608477,0.32102266265325158,0.31186201764350358,0.3678968834064254,0.40111954933665411,0.34822313362863999,0.27675778672488721,0.26296114478703125,0.27357896870765452,0.28350838909767667,0.26505887534563244,0.17745042041363923,0.28705043402744929,0.32739318653133903,0.20954010253112962,0.34930367025495868,0.31691389935494607,0.31601382742839479],\"y\":[0.67540345944832836,0.67072114639860425,0.78529958433519254,0.54517159413040028,0.68628383492195788,0.808368762848511,0.49036557792267527,0.89601705484595395,0.66979366802906282,0.68615149598111569,0.76432254695518143,0.66614664351249964,0.52468975507959714,0.93928981655553878,0.69037963480242037,0.64386383955143811,0.99840400447244748,0.63952536601027421,0.76505664679456342,0.66097252153671893,0.66869306889912694,0.41466715162196122,0.74211441351460838,0.79519570426160446,0.70287874459716126,0.74645668749089977,0.70508030300966096,0.58613605206232344],\"text\":[\"Brand: ALFA ROMEO<br>Exposure: 1,290<br>Claim frequency: 0.31<br>Loss ratio: 67.5%<br>Premium: €567,181<br>Incurred: €383,076<br>Claims: 395\",\"Brand: AUDI<br>Exposure: 11,702<br>Claim frequency: 0.41<br>Loss ratio: 67.1%<br>Premium: €6,128,392<br>Incurred: €4,110,442<br>Claims: 4,745\",\"Brand: BMW<br>Exposure: 9,829<br>Claim frequency: 0.46<br>Loss ratio: 78.5%<br>Premium: €6,020,951<br>Incurred: €4,728,250<br>Claims: 4,487\",\"Brand: CHEVROLET<br>Exposure: 2,646<br>Claim frequency: 0.29<br>Loss ratio: 54.5%<br>Premium: €1,162,202<br>Incurred: €633,600<br>Claims: 766\",\"Brand: CITROEN<br>Exposure: 22,772<br>Claim frequency: 0.28<br>Loss ratio: 68.6%<br>Premium: €8,535,857<br>Incurred: €5,858,021<br>Claims: 6,310\",\"Brand: DACIA<br>Exposure: 1,580<br>Claim frequency: 0.33<br>Loss ratio: 80.8%<br>Premium: €667,074<br>Incurred: €539,242<br>Claims: 523\",\"Brand: DAEWOO<br>Exposure: 1,592<br>Claim frequency: 0.19<br>Loss ratio: 49.0%<br>Premium: €491,488<br>Incurred: €241,009<br>Claims: 303\",\"Brand: FIAT<br>Exposure: 4,809<br>Claim frequency: 0.26<br>Loss ratio: 89.6%<br>Premium: €1,889,314<br>Incurred: €1,692,858<br>Claims: 1,265\",\"Brand: FORD<br>Exposure: 19,950<br>Claim frequency: 0.29<br>Loss ratio: 67.0%<br>Premium: €7,805,001<br>Incurred: €5,227,740<br>Claims: 5,870\",\"Brand: HONDA<br>Exposure: 3,485<br>Claim frequency: 0.36<br>Loss ratio: 68.6%<br>Premium: €1,551,165<br>Incurred: €1,064,334<br>Claims: 1,242\",\"Brand: HYUNDAI<br>Exposure: 6,583<br>Claim frequency: 0.31<br>Loss ratio: 76.4%<br>Premium: €2,617,692<br>Incurred: €2,000,761<br>Claims: 2,046\",\"Brand: KIA<br>Exposure: 4,336<br>Claim frequency: 0.32<br>Loss ratio: 66.6%<br>Premium: €1,813,903<br>Incurred: €1,208,325<br>Claims: 1,392\",\"Brand: LAND ROVER<br>Exposure: 1,392<br>Claim frequency: 0.31<br>Loss ratio: 52.5%<br>Premium: €790,137<br>Incurred: €414,577<br>Claims: 434\",\"Brand: MAZDA<br>Exposure: 2,463<br>Claim frequency: 0.37<br>Loss ratio: 93.9%<br>Premium: €1,046,926<br>Incurred: €983,367<br>Claims: 906\",\"Brand: MERCEDES<br>Exposure: 11,176<br>Claim frequency: 0.40<br>Loss ratio: 69.0%<br>Premium: €6,315,924<br>Incurred: €4,360,385<br>Claims: 4,483\",\"Brand: MINI<br>Exposure: 1,335<br>Claim frequency: 0.35<br>Loss ratio: 64.4%<br>Premium: €621,887<br>Incurred: €400,410<br>Claims: 465\",\"Brand: MITSUBISHI<br>Exposure: 2,367<br>Claim frequency: 0.28<br>Loss ratio: 99.8%<br>Premium: €1,052,144<br>Incurred: €1,050,465<br>Claims: 655\",\"Brand: NISSAN<br>Exposure: 9,465<br>Claim frequency: 0.26<br>Loss ratio: 64.0%<br>Premium: €3,838,653<br>Incurred: €2,454,916<br>Claims: 2,489\",\"Brand: OPEL<br>Exposure: 19,691<br>Claim frequency: 0.27<br>Loss ratio: 76.5%<br>Premium: €7,362,881<br>Incurred: €5,633,021<br>Claims: 5,387\",\"Brand: PEUGEOT<br>Exposure: 20,761<br>Claim frequency: 0.28<br>Loss ratio: 66.1%<br>Premium: €8,019,479<br>Incurred: €5,300,655<br>Claims: 5,886\",\"Brand: RENAULT<br>Exposure: 24,123<br>Claim frequency: 0.27<br>Loss ratio: 66.9%<br>Premium: €9,113,326<br>Incurred: €6,094,018<br>Claims: 6,394\",\"Brand: ROVER<br>Exposure: 1,031<br>Claim frequency: 0.18<br>Loss ratio: 41.5%<br>Premium: €345,985<br>Incurred: €143,469<br>Claims: 183\",\"Brand: SEAT<br>Exposure: 19,547<br>Claim frequency: 0.29<br>Loss ratio: 74.2%<br>Premium: €7,368,450<br>Incurred: €5,468,233<br>Claims: 5,611\",\"Brand: SKODA<br>Exposure: 2,673<br>Claim frequency: 0.33<br>Loss ratio: 79.5%<br>Premium: €1,046,281<br>Incurred: €831,998<br>Claims: 875\",\"Brand: SUZUKI<br>Exposure: 2,386<br>Claim frequency: 0.21<br>Loss ratio: 70.3%<br>Premium: €779,798<br>Incurred: €548,103<br>Claims: 500\",\"Brand: TOYOTA<br>Exposure: 10,790<br>Claim frequency: 0.35<br>Loss ratio: 74.6%<br>Premium: €4,503,259<br>Incurred: €3,361,488<br>Claims: 3,769\",\"Brand: VOLKSWAGEN<br>Exposure: 20,551<br>Claim frequency: 0.32<br>Loss ratio: 70.5%<br>Premium: €8,666,984<br>Incurred: €6,110,920<br>Claims: 6,513\",\"Brand: VOLVO<br>Exposure: 3,475<br>Claim frequency: 0.32<br>Loss ratio: 58.6%<br>Premium: €1,671,932<br>Incurred: €979,980<br>Claims: 1,098\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(8,81,156,1)\",\"opacity\":0.65000000000000002,\"size\":[11.559995769002811,33.251781347269393,30.888583693283973,17.554421118570946,44.232309692500017,13.383685158390199,13.449970792636758,22.84639839073251,41.769334504929127,19.878768014357011,26.090482384548096,21.857438933392757,12.280581719124582,16.968981148539871,32.610611482408522,11.89617513273148,16.648099379268761,30.40066596920656,41.534147133806641,42.49508761786246,45.354330708661422,7.559055118110237,41.403021934901616,17.635583029452508,16.714177189132201,32.129175007671002,42.308695510353566,19.853091180508329],\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(8,81,156,1)\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":43.098381070983812,\"r\":7.9701120797011216,\"b\":40.647571606475722,\"l\":66.151930261519325},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"Brand-level screen for high loss ratio and claim frequency\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":19.128268991282692},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.1634986528698576,0.47043753883305356],\"tickmode\":\"array\",\"ticktext\":[\"0.20\",\"0.30\",\"0.40\"],\"tickvals\":[0.20000000000000001,0.30000000000000004,0.40000000000000002],\"categoryorder\":\"array\",\"categoryarray\":[\"0.20\",\"0.30\",\"0.40\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Claim frequency\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.38540050920305929,1.0292666424189019],\"tickmode\":\"array\",\"ticktext\":[\"40.0%\",\"60.0%\",\"80.0%\",\"100.0%\"],\"tickvals\":[0.40000000000000002,0.60000000000000009,0.80000000000000004,1],\"categoryorder\":\"array\",\"categoryarray\":[\"40.0%\",\"60.0%\",\"80.0%\",\"100.0%\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Aggregate loss ratio\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"shapes\":[],\"showlegend\":false,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"title\":{\"text\":\"Exposure\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"f88c6f513600\":{\"yintercept\":{},\"type\":\"scatter\"},\"f88c67ef4f63\":{\"x\":{},\"y\":{},\"size\":{},\"text\":{}},\"f88c33b13f76\":{\"x\":{},\"y\":{},\"size\":{},\"text\":{},\"label\":{}}},\"cur_data\":\"f88c6f513600\",\"visdat\":{\"f88c6f513600\":[\"function (y) \",\"x\"],\"f88c67ef4f63\":[\"function (y) \",\"x\"],\"f88c33b13f76\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- The bubble chart screens brands by claim frequency, loss ratio, and exposure.\n- Upper-right brands combine higher claim frequency and higher loss ratio, so they represent volatility candidates rather than automatically poor brands; brand can proxy vehicle profile, repair cost, parts availability, and theft attractiveness.\n- Among brands with exposure at least 1,000, Mitsubishi and Mazda have the highest aggregate loss ratios, about 99.8% and 93.9% respectively.\n- Large upper-right bubbles should be prioritised for deeper investigation because they combine underwriting impact with enough exposure to matter.\n:::\n\n### Statistical validation\n\nThe dataset is large and skewed, so visual signals are validated with non-parametric and categorical tests:\n\n-   **Kruskal-Wallis tests** check whether capped individual loss ratio differs across segment groups.\n-   **Chi-square tests** check whether claim occurrence differs across segment groups.\n-   **Spearman correlations** check monotonic relationships between numerical variables and capped loss ratio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_vars <- c(\n  \"policy_type\", \"bonus_score\", \"driver_age_band\", \"vehicle_age_band\",\n  \"fuel_type\", \"circulation_area\", \"payment_frequency\", \"year\"\n)\n\nkw_tbl <- map_dfr(test_vars, \\(v) {\n  kt <- kruskal.test(as.formula(paste(\"loss_ratio_cap ~\", v)), data = motor)\n  tibble(\n    test = \"Kruskal-Wallis\",\n    variable = v,\n    statistic = unname(kt$statistic),\n    p_value = kt$p.value\n  )\n})\n\nchi_tbl <- map_dfr(test_vars, \\(v) {\n  ct <- chisq.test(table(motor[[v]], motor$claim_flag))\n  tibble(\n    test = \"Chi-square\",\n    variable = v,\n    statistic = unname(ct$statistic),\n    p_value = ct$p.value\n  )\n})\n\nvalidation_tbl <- bind_rows(kw_tbl, chi_tbl) |>\n  mutate(p_value_label = format.pval(p_value, digits = 3)) |>\n  select(test, variable, statistic, p_value_label)\n\nkable(validation_tbl, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|test           |variable          | statistic|p_value_label |\n|:--------------|:-----------------|---------:|:-------------|\n|Kruskal-Wallis |policy_type       |   7303.95|<2e-16        |\n|Kruskal-Wallis |bonus_score       |    287.43|<2e-16        |\n|Kruskal-Wallis |driver_age_band   |    267.02|<2e-16        |\n|Kruskal-Wallis |vehicle_age_band  |    303.51|<2e-16        |\n|Kruskal-Wallis |fuel_type         |    799.21|<2e-16        |\n|Kruskal-Wallis |circulation_area  |    211.66|<2e-16        |\n|Kruskal-Wallis |payment_frequency |    399.63|<2e-16        |\n|Kruskal-Wallis |year              |    201.00|<2e-16        |\n|Chi-square     |policy_type       |   6638.42|<2e-16        |\n|Chi-square     |bonus_score       |    297.19|<2e-16        |\n|Chi-square     |driver_age_band   |    463.27|<2e-16        |\n|Chi-square     |vehicle_age_band  |    437.03|<2e-16        |\n|Chi-square     |fuel_type         |    817.15|<2e-16        |\n|Chi-square     |circulation_area  |    225.88|<2e-16        |\n|Chi-square     |payment_frequency |    463.95|<2e-16        |\n|Chi-square     |year              |    197.87|<2e-16        |\n\n\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- Group-difference tests provide statistical support for the visual segment comparisons.\n- `policy_type` is the strongest validation signal in both capped loss-ratio differences and claim-occurrence differences, reinforcing the importance of coverage structure.\n- Fuel type, payment frequency, driver age band, vehicle age band, bonus score, circulation area, and year are also statistically significant, matching the dictionary groups for driver/vehicle, policy behaviour, geography, and time.\n- Because the dataset is large, p-values should be interpreted with exposure, visual effect size, and business relevance rather than treated as sufficient evidence on their own.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorr_tbl <- map_dfr(\n  c(\"driver_age\", \"vehicle_age\", \"age_driving_licence\", \"vehicle_value\",\n    \"seats\", \"power_to_weight_ratio\", \"total_premium\"),\n  \\(v) {\n    ct <- suppressWarnings(cor.test(motor[[v]], motor$loss_ratio_cap,\n                                    method = \"spearman\", exact = FALSE))\n    tibble(variable = v, spearman_rho = unname(ct$estimate), p_value = ct$p.value)\n  }\n) |>\n  mutate(p_value_label = format.pval(p_value, digits = 3)) |>\n  arrange(desc(abs(spearman_rho)))\n\nkable(corr_tbl |> select(variable, spearman_rho, p_value_label), digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|variable              | spearman_rho|p_value_label |\n|:---------------------|------------:|:-------------|\n|total_premium         |        0.206|<2e-16        |\n|vehicle_value         |        0.070|<2e-16        |\n|power_to_weight_ratio |       -0.035|<2e-16        |\n|vehicle_age           |       -0.029|<2e-16        |\n|driver_age            |       -0.025|<2e-16        |\n|seats                 |        0.017|<2e-16        |\n|age_driving_licence   |        0.001|0.705         |\n\n\n:::\n:::\n\n\n::: {.observation-box}\n**Observations**\n\n- Total premium has the strongest monotonic relationship with capped loss ratio, but the relationship is still moderate with Spearman rho around 0.206.\n- Most demographic and vehicle correlations are small even when statistically significant.\n- `age_driving_licence` is not practically useful as a monotonic predictor here; its Spearman rho is close to zero and the field records licence-issue year rather than years of driving experience.\n- Practical interpretation should therefore combine visual difference, exposure, effect direction, and business relevance instead of relying only on significance tests.\n:::\n\n## Key findings\n\nThe objective of this report is to use visual analytics to identify portfolio segments associated with weaker underwriting profitability and higher volatility. The main findings are:\n\n1.  **The portfolio is profitable overall, but the margin is exposed to loss volatility.** Across 354,140 policy-year records, the portfolio generates about EUR31.2 million underwriting profit before expenses and an aggregate loss ratio of about 70.3%. However, only about 14.3% of records have claims, so profitability is sensitive to a relatively small claim-producing tail.\n2.  **Profitability deteriorates in 2024.** The aggregate loss ratio increases from about 65.6% in 2022 and 66.5% in 2023 to about 74.7% in 2024. This indicates that incurred losses are growing faster than premium and that the latest year should be treated as an early-warning period.\n3.  **Policy type is the strongest and most defensible segmentation signal.** Comprehensive covers have materially weaker results than third-party-focused covers. `COMP_N` has the highest aggregate loss ratio at about 93.9%, and the year-by-policy heatmap shows `COMP_N` exceeding break-even in 2024 at about 102.4%.\n4.  **Secondary segment variables explain where profitability and volatility are concentrated.** Non-good bonus scores, diesel vehicles, urban circulation areas, and shorter payment frequencies show higher loss ratios than their comparison groups. These are useful underwriting screening variables, but they should be interpreted together with exposure and policy mix.\n5.  **Volatility is concentrated in claim frequency and upper-tail outcomes rather than in the typical policy-year record.** Boxplots, capped loss-ratio distributions, policy-type comparisons, and brand-level bubbles show that most records remain low-loss, while a smaller set of claim-heavy segments drives the high-loss tail.\n6.  **The visual signals are statistically supported but not causal.** Kruskal-Wallis and chi-square tests support group differences across key segmentation variables. Because the dataset is large and observational, the results should guide deeper underwriting investigation rather than be used as standalone pricing rules.\n\n## Recommendations\n\n-   **Prioritise comprehensive-cover review.** Monitor `COMP_N` and `COMP_E` separately from the rest of the portfolio, with particular attention to 2024 `COMP_N` performance. Review claim frequency, claim severity, excess structure, and premium adequacy before making portfolio-wide pricing changes.\n-   **Use 2024 as an early-warning trigger.** Build a recurring year-by-segment loss-ratio monitor so that deterioration by policy type, bonus score, fuel type, circulation area, and payment frequency is detected before it becomes an aggregate profitability issue.\n-   **Apply segment screening, not automatic repricing.** Treat high-loss brand, diesel, urban, non-good bonus-score, and shorter-payment-frequency groups as candidates for deeper review. Validate whether the observed differences remain after controlling for exposure, policy type, vehicle age, driver age, and claim mix.\n-   **Strengthen volatility management.** Track high-loss policy rate, claim frequency, severity, and capped loss ratio in addition to aggregate loss ratio. These measures align better with the report objective because they reveal tail-risk segments hidden by portfolio-level profitability.\n-   **Enrich the portfolio data before final underwriting action.** Add external geography, traffic-density, weather, theft-risk, and vehicle repair-cost indicators to explain why specific segments underperform and to separate true risk effects from product-mix effects.\n\n## References\n\n-   ISSS608 Take-home Exercise 1 brief: <https://isss608-ay2025-26apr.netlify.app/th_ex/th_ex1>\n-   Motor insurance portfolio data: <https://data.mendeley.com/datasets/sw4jmdb2sm/1>\n\n",
    "supporting": [
      "TH_Ex1_report_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}