---
title: "Hands-on Exercise 5.2: Visual Correlation Analysis"
author: "Cao Jinming"
date: "16 May 2026"
date-modified: "last-modified"
execute:
  eval: true
  echo: true
  warning: false
format: html
---

```{r}
pacman::p_load(corrplot, ggstatsplot, tidyverse)
```

```{r}
wine <- read_csv("../data/r4va/wine_quality.csv")
```

```{r}
pairs(wine[,1:11])
```

```{r}
pairs(wine[,2:12])
```

```{r}
pairs(wine[,2:12], upper.panel = NULL)
```

```{r}
pairs(wine[,2:12], lower.panel = NULL)
```

```{r}
panel.cor <- function(x, y, digits=2, prefix="", cex.cor, ...) {
usr <- par("usr")
on.exit(par(usr))
par(usr = c(0, 1, 0, 1))
r <- abs(cor(x, y, use="complete.obs"))
txt <- format(c(r, 0.123456789), digits=digits)[1]
txt <- paste(prefix, txt, sep="")
if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
text(0.5, 0.5, txt, cex = cex.cor * (1 + r) / 2)
}

pairs(wine[,2:12], 
      upper.panel = panel.cor)
```

```{r}
ggstatsplot::ggcorrmat(
  data = wine, 
  cor.vars = 1:11)
```

```{r}
ggstatsplot::ggcorrmat(
  data = wine, 
  cor.vars = 1:11,
  ggcorrplot.args = list(outline.color = "black", 
                         hc.order = TRUE,
                         tl.cex = 10),
  title    = "Correlogram for wine dataset",
  subtitle = "Four pairs are no significant at p < 0.05"
)
```

```{r}
# Shorter display labels make the grouped correlogram readable in HTML.
wine_corr_display <- wine |>
  rename(
    `fixed acid` = `fixed acidity`,
    `volatile acid` = `volatile acidity`,
    `free SO2` = `free sulfur dioxide`,
    `total SO2` = `total sulfur dioxide`
  )

ggplot_component <- list(
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 9, lineheight = 1.1),
    plot.caption = element_text(size = 8),
    axis.text.x = element_text(size = 7, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 7)
  )
)
```

```{r}
#| fig-width: 10
#| fig-height: 14
#| out-width: "100%"
grouped_ggcorrmat(
  data = wine_corr_display,
  cor.vars = 1:11,
  grouping.var = type,
  type = "robust",
  p.adjust.method = "holm",
  plotgrid.args = list(ncol = 1),
  ggcorrplot.args = list(
    outline.color = "black",
    hc.order = TRUE,
    tl.cex = 8,
    pch.cex = 2
  ),
  ggplot.component = ggplot_component,
  annotation.args = list(
    tag_levels = "a",
    title = "Correlogram for wine dataset",
    subtitle = "Measures: alcohol, sulphates, fixed acid, volatile acid, citric acid, chlorides, residual sugar, density, free SO2, total SO2, and pH",
    caption = "Dataset: UCI Machine Learning Repository"
  )
)
```

```{r}
wine.cor <- cor(wine[, 1:11])
```

```{r}
corrplot(wine.cor)
```

```{r}
corrplot(wine.cor, 
         method = "ellipse")
```

```{r}
corrplot(wine.cor, 
         method = "ellipse", 
         type="lower")
```

```{r}
corrplot(wine.cor, 
         method = "ellipse", 
         type="lower",
         diag = FALSE,
         tl.col = "black")
```

```{r}
corrplot.mixed(wine.cor, 
               lower = "ellipse", 
               upper = "number",
               tl.pos = "lt",
               diag = "l",
               tl.col = "black")
```

```{r}
corrplot.mixed(wine.cor, 
               lower = "ellipse", 
               upper = "number",
               tl.pos = "lt",
               diag = "l",
               tl.col = "black")
```

```{r}
wine.sig = cor.mtest(wine[, 1:11], conf.level= .95)
```

```{r}
corrplot(wine.cor,
         method = "number",
         type = "lower",
         diag = FALSE,
         tl.col = "black",
         tl.srt = 45,
         p.mat = wine.sig$p,
         sig.level = .05)
```

```{r}
corrplot.mixed(wine.cor, 
               lower = "ellipse", 
               upper = "number",
               tl.pos = "lt",
               diag = "l",
               order="AOE",
               tl.col = "black")
```

```{r}
corrplot(wine.cor, 
         method = "ellipse", 
         tl.pos = "lt",
         tl.col = "black",
         order="hclust",
         hclust.method = "ward.D",
         addrect = 3)
```
